### ISSUE TITLE
Error on trying to open a file previously edited in 3.3.5 (in OS 11.4)

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#463] opened 2021-05-26 16:33 UTC
<img width="1164" alt="Screen Shot 2021-05-26 at 12 31 52 PM" src="https://user-images.githubusercontent.com/13629122/119697656-6e137f80-be1e-11eb-83f8-1e984984ca92.png">

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6548278/SignStreamOut.txt)

**Comment by cneidle** [comment] 2021-05-26 16:39
I reopened SignStream and was able to reopen that same file.  However, the video file had to be reselected.  Don't know if that contributed to the problem above...

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-26 19:40
Email us video and collection file.

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-26 19:51
I might have just observed this.

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-26 19:52
I got the error as soon as I did an open on an old collection file.

Do you get this error at the same time...or...do you get this after changing the file location and trying to save the macro edit settings?

**Comment by foltik** [comment] 2021-05-26 20:55
Fixed as of `SignStream3_3.7.0_pre_2021_05_26_1633_f4b57607`.

**Comment by cneidle** [comment] 2021-05-27 15:48
Happened again- have not changed anything - simply tried to open a previously annotated file from its existing location.

10.12.6 - May 27

<img width="1057" alt="Screen Shot 2021-05-27 at 11 45 22 AM" src="https://user-images.githubusercontent.com/13629122/119857099-4802e380-bee1-11eb-9cc3-0b2457d1639f.png">


[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6555246/SignStreamOut.txt)

**Comment by foltik** [comment] 2021-05-27 16:43
This is an issue with loading that specific collection file, not the media player as above. Can you send it?

**Comment by cneidle** [comment] 2021-05-27 16:48
Yes, I can send the file, but I have been able subsequently to open that same file
without a problem, so it is presumably not something inherent to the file.

**Comment by foltik** [comment] 2021-05-27 18:27
Looks like this error is caused by some internal state getting messed up when opening a new collection with one already loaded.

I'm not able to get this to happen, is it reproducible with a certain set of steps?

**Comment by gregorydimitriadis** [comment] 2021-05-27 19:05
@cneidle also can you point/link us to the video for the collection? thanks in advance

**Comment by cneidle** [comment] 2021-05-27 21:12
It has happened more than once, I think on trying to open one file while another was open, but I am not able to reproduce it with any particular sequence of steps.

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-29 02:22
The original error window above is different from the second error window above.

Believe this relates to the validator.  If clicking "Cancel" on the Validation popup, the above window and error message appears.

Closing this ticket.

If changes are desired to what happens when clicking "Cancel" please add to issue...

https://github.com/DCS-LCSR/SignStream3/issues/467

**Closed as completed by douglas-motto-at-rutgers** 2021-05-29 02:22 UTC
Labels: SS3-May-26, THU-am-MAY-27-v3
