### ISSUE TITLE
Jack - 2-2-21.     Clicking on gloss item to select

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#399] opened 2021-02-02 17:19 UTC
it is extremely difficult to select a gloss item by clicking on it.  It should be sufficient to click on the gloss item or the line.  Only seems to work by clicking on the line.

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-09 14:04
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
The focusing behavior for glosses has not changed from that of 3.3.1
Be careful as click and drag will NOT focus a gloss....must click without moving.

Closing.

**Comment by cneidle** [comment] 2021-05-09 14:09
I don't know what you're referring to by "click and drag".  We don't do that with glosses.
The problem was (and perhaps still is) similar to what has been occurring with trying to enter the 
gloss in the first place:  there has been an inappropriate sensitivity to height.  You should be able to
Option click at any height within the gloss field, and you should be able to click on a gloss at any
height (not necessarily on the line beneath it) to select the gloss.  I can check this with the latest
version when I receive it.

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-09 14:20
Click and drag does not create any events....option, click and drag does create or edit for all events but glosses.

Click and drag moves the greenbar without focusing or defocusing any events.

Closing.  After testing...open new issue if found not to still work.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-09 14:20 UTC
Labels: cannot reproduce, Jack's implementation, For Carol to test

**Comment by cneidle** [comment] 2021-05-09 14:41
OK, will test on the next version.

FYI - these have been problems still with ALL recent versions I have tested:

The problem was (and perhaps still is) similar to what has been occurring with trying to enter the
gloss in the first place: there has been an inappropriate sensitivity to height. You should be able to
Option click at any height within the gloss field, and you should be able to click on a gloss at any
height (not necessarily on the line beneath it) to select the gloss. I can check this with the latest
version when I receive it.

**Comment by douglas-motto-at-rutgers** [comment] 2021-06-07 04:27
We have not experienced what you are describing since at least February.

I am able to option click at any height with in the dom gloss or ndom gloss field line and it opens the text input to enter the gloss name.  (not just the line beneath it).

To "focus" a gloss, anywhere the line exists from the top to bottom of the field line can be clicked.  If no line exists yet, as for new glosses, anywhere the word exists from top to bottom may be clicked.

You can not currently click a sign word outside the line.  This is the same behavior as 3.3.1.

You can not click and drag to select a gloss.  The click and drag process means you press the mouse down and move even slightly the mouse before releasing the mouse button.  If you click and drag, this moves the greenbar and does NOT focus anything.  To focus, you need to click or tap the mouse button without moving the mouse.  This is the same behavior as was in 3.3.1.

If what I describe here is still not what you are experiencing then you'll need to demonstrate this so we can better understand what is happening.

**Comment by douglas-motto-at-rutgers** [comment] 2021-06-07 04:30
Side note.  Any issue marked as "closed" is no longer looked at.

Two options if the issue is still not solved.

a) Re-open the issue.

b) Open a new issue (referring to the old issue).  This is preferred as some old issues are cluttered with several problems.  Better to make a clean description with an updated state of things.
