### ISSUE TITLE
Deleting a gloss

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#231] opened 2018-06-11 19:01 UTC
I am working on U6 of Cory 115 and I noticed some glosses that were two-handed but what we were actually seeing was a one-handed gloss. As I went into the morph-info of the glosses, everything was entered as a two-handed sign yet when I pressed "bypass sign bank" the glosses still appeared as one handed. The two signs are (2h)IX-3p:i As I tried to delete one, it deleted both. It was like these two glosses were actually acting as the same entity. I haven't tried to enter the correct data yet but I will once you can see what I am talking about. 

![screen shot 2018-06-11 at 2 52 47 pm](https://user-images.githubusercontent.com/38887034/41251512-25b5a7f2-6d88-11e8-9b91-a9ea7f4d1977.png)

![screen shot 2018-06-11 at 2 53 03 pm](https://user-images.githubusercontent.com/38887034/41251515-282f1d24-6d88-11e8-926b-3f75687eb1b8.png)

![screen shot 2018-06-11 at 2 53 24 pm](https://user-images.githubusercontent.com/38887034/41251521-2a21db9e-6d88-11e8-94f3-6b0d2d8b0675.png)

![screen shot 2018-06-11 at 2 53 31 pm](https://user-images.githubusercontent.com/38887034/41251523-2bb27b62-6d88-11e8-8d32-d3c25cba25ba.png)

**Comment by cneidle** [comment] 2018-06-11 19:12
Hi Indya,

That had been entered as a 2-handed sign (incorrectly!),
but with the relationship between the right and left hand
unlocked, and the 2 hands had been time-adjusted separately.

You should just delete that sign and re-enter it properly.

I can explain this to you tomorrow :-)

But this is not a bug.

Thanks,
 Carol

**Comment by gregorydimitriadis** [comment] 2018-06-11 21:25
@cneidle should I close this?

**Comment by cneidle** [comment] 2018-06-11 21:35
yes, please close.  thanks.

**Closed as completed** 2018-06-11 21:35 UTC
