### ISSUE TITLE
.ss3 Files without Specified Lookup File Directory Do Not Have Working Horizontal Scroll Bars

### ISSUE THREAD

**Issue by travisnguyen** [DCS-LCSR/SignStream3#249] opened 2018-11-29 20:13 UTC
Hi everyone,

This doesn't seem to be a bug that affects functionality of the program too much, but I am noting it for posteriority's sake.

Also, this bug doesn't seem to be reproduceable. Trying to reproduce it by removing the specified lookup file directory (at Macro Unit -> Edit Macro Unit -> Lookup) for an .ss3 file either causes the program to crash, or the lookup button is grayed out and unaccessible.

Tested using Cory 107 and version 3.1.2.

Description:

1. Opening an .ss3 file with no specified lookup directory causes the horizontal scroll bar not to appear.

![screen shot 2018-11-29 at 2 10 19 pm](https://user-images.githubusercontent.com/4441077/49248647-3d3a6700-f3e8-11e8-8571-0fea25a4f997.png)

2. Selecting an utterance on the left navigation bar (that isn't the utterance that you are currently on) will cause the horizontal scroll bar to appear:

![screen shot 2018-11-29 at 2 02 30 pm](https://user-images.githubusercontent.com/4441077/49248697-53e0be00-f3e8-11e8-8393-55bcd8c88465.png)

3. However, trying to drag the horizontal scroll bar will cause the horizontal bar to disappear, and the utterance will not move on the timeline.

![screen shot 2018-11-29 at 2 10 19 pm](https://user-images.githubusercontent.com/4441077/49248725-65c26100-f3e8-11e8-81e7-d9925350222c.png)

Repeat steps 2 and 3 ad infinitum.

**Comment by gregorydimitriadis** [comment] 2018-11-30 15:34
@travisnguyen 

Does taking out the lookup directory involve removing the attached video file? (i.e. is there still a video attached after doing this) -- I know that without a video some of these things you reported could occur and are expected to (i.e. bad state)

**Comment by cneidle** [comment] 2018-12-02 19:30
I don’t understand what is meant by “taking out the lookup directory”.

But definitely, yes, a video FILE must be selected in order for things
to display properly.

Travis - let’s discuss this on Tuesday.

**Comment by travisnguyen** [comment] 2018-12-04 18:19
@gregorydimitriadis Yes; after removing the lookup directory, there is no video attached.

**Comment by gregorydimitriadis** [comment] 2019-05-01 14:36
Hi @travisnguyen @cneidle 

For this, I can only reproduce this by opening the collection (sent from BU) initially, where the video is not associated because it cannot find the file. In that case, in the lack of a video, the application acts as you describe here. This is expected behavior from the known issue of not having the collection associated with the video. Is this the same on your end?

Once I associate the proper video, then the app runs as expected. Beyond this, is there anything which needs fixing as far as the existing lookup functionality? I also am not sure what "taking out the lookup directory" means exactly (other than possibly what I describe in the previous paragraph about not finding that lookup directory to begin with).

(I know we have issue https://github.com/DCS-LCSR/SignStream3/issues/171 open regarding a more full refactoring of the lookup process, and we have emailed about this a bit too, but if we don't wish to do that at this point then this issue may be moot).

**Comment by cneidle** [comment] 2019-05-01 15:10
I am a bit confused about the vocabulary being used in this discussion.

When a collection is opened, if the videos are not associated,
then they need to be selected manually and attached before
the proper timescale will be displayed for the collection.

The “lookup” function was intended to help the user find
the videos.  In the original version of SIgnStream, launching
“lookup” would result in the program checking specific directories
to try to find the videos. 

I had suggested to Greg at some point making use of a local file 
that would keep track of directories in which videos are typically stored
on the local computer.

The lookup function was never fully implemented.
I’m not sure where that stands right now.  

What the lookup function does now is pretty useless.
It looks only in the immediate folder requested by the user, 
not in subfolders

So for example, I have all the movie files organized as follows:




But if I use the lookup function to search within that higher-level movie
folder, it finds nothing, because it does not look in sub-folders.





It is easier to find and select the movie files manually.

The current lookup function does not remember previous
locations of movie files, and it does not look in subfolders,
so it is not very helpful.

This is not going to be fixed for the next release, but if the
lookup function is to be useful, these are the kinds of changes 
that would need to be made.

I don’t think there is anything that needs to be done in the immediate,
however — unless I am missing something.

Thanks!
  Carol

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-07 16:35
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Lookup has been removed.

Closing.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-07 16:35 UTC
Labels: wontfix
