### ISSUE TITLE
Disappearing Data

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#218] opened 2018-05-14 16:18 UTC
It seems as though there is an issue displaying data. I am currently working on file 82 of Rachel/Jonathan dialog. I have started entering non-manual information (head, face, grammar, etc) for the Jonathan utterances. I have completed utterances 1-4. If I click on these utterances one by one, all the data and coded information is there. However, if I just scroll from one utterance to the next all the non-manual information seems to have disappeared. The first screenshot is the data that is actually there and the second screenshot is what we see (or aren't seeing) when scrolling from one utterance to the next. 

![screen shot 2018-05-14 at 12 12 38 pm](https://user-images.githubusercontent.com/38887034/40009742-d7de3274-5770-11e8-8a43-d61d8e446883.png)

![screen shot 2018-05-14 at 12 12 15 pm](https://user-images.githubusercontent.com/38887034/40009763-e04d0e4e-5770-11e8-840b-22d96839bbdf.png)

**Comment by gregorydimitriadis** [comment] 2018-05-25 15:20
@bugspotter33 do the nonmanual fields in this case come back when hitting the "show non-empty" button in the nonmanual fields section? (the blue button to the right of the plus and minus buttons)

**Comment by bugspotter33** [comment] 2018-05-25 15:31
Okay so I found the button and yes the fields do reappear once you click that button.

**Comment by gregorydimitriadis** [comment] 2018-05-25 15:46
@bugspotter33 Thanks - appears it's a bug, then, as that action should occur automatically.

**Comment by gregorydimitriadis** [comment] 2018-05-25 15:46
@bugspotter33 Correction - it shouldn't occur automatically on scroll, but the fields disappearing definitely should not happen.

**Comment by gregorydimitriadis** [comment] 2018-08-01 13:59
Likely related to #221

**Comment by gregorydimitriadis** [comment] 2018-08-17 15:18
@cneidle I think this one is technically not a bug, right? I can see what was seen in the initial report, and on scrolling back to U29 and clicking "show all non-empty" I see "eye brows" reappear. That appears to be working correctly.

**Comment by cneidle** [comment] 2018-08-17 15:25
The fields should not disappear.  That is (or was) a bug.

Choosing Next Utterance, or Previous Utterance, or clicking on a specific utterance on the left, or using the arrow keys to select the next or previous utterance:  All of those things should automatically invoke "show non-empty" so that when the user chooses a specific utterance to view, the user also sees the data associated with that utterance.  Without that, the user would have to click "display non-empty" every time they want to view an utterance (or risk missing seeing data that they don't realize is there)--both of which are undesirable.

**Comment by gregorydimitriadis** [comment] 2018-08-17 15:35
I see. In that case, I cannot reproduce the fields disappearing entirely while scrolling.

**Comment by cneidle** [comment] 2018-08-17 15:52
It recurs for me.

Note that this file, 82, has multiple temporal partitions/segment tiers:


<img width="1062" alt="screen shot 2018-08-17 at 11 47 38 am" src="https://user-images.githubusercontent.com/13629122/44275978-35c5c800-a214-11e8-92b3-6a6b1749e4ad.png">



Here is the view when I scroll from utterance 2.  Note what is visible in the utterance that
has the translation “I’m curious… "

<img width="1351" alt="screen shot 2018-08-17 at 11 47 00 am" src="https://user-images.githubusercontent.com/13629122/44275987-3c543f80-a214-11e8-9a4f-561e0fb4d0b9.png">



If I click on that utterance, however, all the rest of the information becomes visible.

<img width="1336" alt="screen shot 2018-08-17 at 11 47 16 am" src="https://user-images.githubusercontent.com/13629122/44275996-424a2080-a214-11e8-9893-bc251f23202e.png">


I suspect that the screen is just failing to fully redraw when the scrolling stops.

I am attaching a copy of this file.

Thanks,
 Carol

**Comment by cneidle** [comment] 2018-08-17 15:56
Pictures for above

<img width="1062" alt="screen shot 2018-08-17 at 11 47 38 am" src="https://user-images.githubusercontent.com/13629122/44276075-76bddc80-a214-11e8-82bc-9dd9f6cdc80b.png">

<img width="1351" alt="screen shot 2018-08-17 at 11 47 00 am" src="https://user-images.githubusercontent.com/13629122/44276081-7ae9fa00-a214-11e8-8ed6-2f5868047c0a.png">

<img width="1336" alt="screen shot 2018-08-17 at 11 47 16 am" src="https://user-images.githubusercontent.com/13629122/44276090-80474480-a214-11e8-8c1a-9eb043e5625a.png">

**Comment by gregorydimitriadis** [comment] 2018-08-17 16:15
@cneidle This is different than the original reported thing. In the original, it was the actual field labels for everything which disappeared. In this example, all the field labels remain (for the fields which were showing for the "selected" utterance - in your case U2) but there is nothing showing for them  as you scrolled into the next utterances. On clicking one of those next utterances, it simulates clicking "show non-empty" and shows the appropriate stuff for what's on screen. This looks like correct behavior to me.

**Comment by cneidle** [comment] 2018-08-17 20:03
Yes, you are correct.  Sorry.

This is not the bug that was reported.

I did witness it myself, however (as Indya was
doing the annotations).

It was for a file packed with information, and on a 
not very powerful computer.  

My impression at the time was that screen redrawing
had just failed to repaint the upper portion of the
window.

FWIW,
 Carol

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-07 14:52
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
appears to be a non-issue.

some of the hiding/showing has been redesigned too.

closing.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-07 14:52 UTC
Labels: bug, priority HIGH, cannot reproduce
