### ISSUE TITLE
Testing second version of the day - 5/3/21:  Setting start/end of gloss not working properly

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#422] opened 2021-05-04 00:31 UTC
I type in the gloss, and then attempt to set the start.  Does not happen.
<img width="558" alt="Screen Shot 2021-05-03 at 8 27 55 PM" src="https://user-images.githubusercontent.com/13629122/116948822-81339500-ac4e-11eb-8b8b-68a6eaa20c0c.png">

note: this was with OS 10.12.6

**Comment by foltik** [comment] 2021-05-05 15:03
Unable to reproduce in SignStream4_4.0.0_convergence_2021_04_30_1705_4dc238f4, will need to be demonstrated to fix.

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-09 20:17
Also unable to reproduce in SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17.  

Closing for now.  Reopen if seen existing after trying newer version.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-09 20:17 UTC
Labels: V2 - 5/3/21
