### ISSUE TITLE
Can't delete non-manual - est. 12 hours

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#222] opened 2018-06-06 13:44 UTC
I am working in the Cory file 113 U16 and I have come across a non-manual that I can't delete. When I click on it it doesn't highlight red and I tried to right click to delete it and nothing is working. The event is a raised non-manual event at the very beginning of the sentence and I think there is also an onset underneath. 

![screen shot 2018-06-06 at 9 41 23 am](https://user-images.githubusercontent.com/38887034/41041806-1f1f448e-696e-11e8-80fc-b9e7ae5f295f.png)

**Comment by gregorydimitriadis** [comment] 2018-06-06 15:28
@bugspotter33 @cneidle can you please send the collection? Thanks in advance

**Comment by bugspotter33** [comment] 2018-06-13 16:55
Cory 115 U30 same issue (can't delete the non-manual) in the field hp tilt -right  at the beginning of the utterance

![screen shot 2018-06-13 at 12 55 22 pm](https://user-images.githubusercontent.com/38887034/41366095-0d4f8e8a-6f09-11e8-8293-38da7e760013.png)

**Comment by bugspotter33** [comment] 2018-07-10 15:27
Found another case in U29 Jonathan file 90. Can't delete the one framed blink.

![screen shot 2018-07-10 at 11 26 26 am](https://user-images.githubusercontent.com/38887034/42520403-30afc0bc-8434-11e8-89a0-5c379b2eeeb6.png)

**Comment by bugspotter33** [comment] 2018-07-10 15:31
This last bug (U29 J90) we were able to delete. It was difficult to select even after being zoomed in as much as possible.

**Comment by aimeeaylward** [comment] 2018-07-16 16:44
I have found a case of this in Jonathan 93 U1, a -wide eye apert event that I'm unable to delete. I was unable to select it even when zooming in fully.

**Comment by cneidle** [comment] 2018-08-04 19:38
am increasing priority

**Comment by gregorydimitriadis** [comment] 2018-11-28 18:46
@cneidle @bugspotter33 cannot reproduce this one  -- I suspect the issue might have something to do with the odd onset where it's not supposed to be, or one-frame's behaving oddly. The collection I received did not have the onset under the regular nonmanual to test it.

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-07 15:18
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

can delete non-manual fields.  Assuming this is no longer an issue.

Closing.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-07 15:18 UTC
Labels: bug, complete, priority MED, released
