### ISSUE TITLE
Discrepancy in display when setting/viewing end frame of an utterance

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#435] opened 2021-05-13 13:38 UTC
11.3.1 

I set the end frame of the utterance to a frame that is before the black region (1st screen shot below).
But when I play the utterance, it plays through to a black frame (2nd screen shot below).
The frame information displayed is the same in both cases.

Same within the utterance - going to the end also shows a black frame.

<img width="533" alt="Screen Shot 2021-05-13 at 9 35 49 AM" src="https://user-images.githubusercontent.com/13629122/118133314-af437280-b3ce-11eb-9535-eaa5f10af563.png">

<img width="560" alt="Screen Shot 2021-05-13 at 9 35 57 AM" src="https://user-images.githubusercontent.com/13629122/118133338-b66a8080-b3ce-11eb-9cb0-f7067ddef712.png">

Note - this black frame apears when playing the utterance, but "go to end" of utterance does not do this.
Same within the utterance window - playing the utterance shows a black frame at the end, but go to end of utterance does not.

**Comment by foltik** [comment] 2021-05-13 17:09
Fixed in `SignStream4_4.1.0_pre_2021_05_13_1245_71f3a686`

**Comment by cneidle** [comment] 2021-05-14 14:02
Not fixed in 3.7

Go to end shows black whereas play entity does not.

<img width="639" alt="Screen Shot 2021-05-14 at 10 00 37 AM" src="https://user-images.githubusercontent.com/13629122/118281532-4d047380-b49b-11eb-82ec-3f13c1e422bc.png">

**Comment by foltik** [comment] 2021-05-14 14:16
@cneidle A black frame is only displayed at the end of the video since the stream has ended and there are no more frames to display. This was happening erroneously at the end of utterances, which is what I fixed.

**Comment by cneidle** [comment] 2021-05-14 14:18
What I just reported is at the end of utterance.

**Comment by foltik** [comment] 2021-05-14 14:21
I think the black screen in your latest screenshot is just part of the video, I still see the yellow timestamp text.

**Comment by cneidle** [comment] 2021-05-14 14:26
It is part of the video, but not part of the utterance as I had set the end frame to be the previous one.  Play entity displays a non-blank screen at the end, as I had set it.

**Comment by cneidle** [comment] 2021-05-14 14:36
Here is another set of screenshots showing this happening (although it happens sometimes but not always):

Entity - Set end. Play end.  Look like this:

<img width="613" alt="Screen Shot 2021-05-14 at 10 34 27 AM" src="https://user-images.githubusercontent.com/13629122/118286181-30b70580-b4a0-11eb-8ed4-e9bd19461991.png">


Go to end.  Looks like this:

<img width="588" alt="Screen Shot 2021-05-14 at 10 34 55 AM" src="https://user-images.githubusercontent.com/13629122/118286197-357bb980-b4a0-11eb-906f-2f40d3862967.png">

**Comment by foltik** [comment] 2021-05-14 14:41
Could you send a screenshot of the video and main window when setting the end time of the utterance? There I see the black frame on the video says 27;07 (27*30 + 7 = 817 frames) which matches with the end time of the utterance showing in SignStream.

Maybe the video is displaying the incorrect frame when you set the end time of the utterance, since it looks like the actual end time ends up actually being on a black frame?

**Comment by foltik** [comment] 2021-05-14 14:43
Comparing the yellow frame numbers in the video vs. the event start/end in SignStream should help determining exactly where any discrepancy is happening.

**Comment by cneidle** [comment] 2021-05-14 15:08
Displayed from 'go to end of entity' 

<img width="832" alt="Screen Shot 2021-05-14 at 11 05 32 AM" src="https://user-images.githubusercontent.com/13629122/118290403-678f1a80-b4a4-11eb-963b-c41ac85a8e29.png">

Displayed as last frame from 'play entity' 

<img width="829" alt="Screen Shot 2021-05-14 at 11 05 49 AM" src="https://user-images.githubusercontent.com/13629122/118290406-6827b100-b4a4-11eb-824f-bcf6477e57e3.png">

Note that the numbers displayed in SignStream are the same, although
these frames differ by 1.

**Comment by cneidle** [comment] 2021-05-14 16:08
Within an utterance, going to the end vs. playing an event or entity results in a discrepancy of one or two frames (seems a bit random).

Go to end - goes to 13 or 14

<img width="705" alt="Screen Shot 2021-05-14 at 12 04 33 PM" src="https://user-images.githubusercontent.com/13629122/118297745-914c3f80-b4ac-11eb-910a-242ca14c2b9a.png">

<img width="605" alt="Screen Shot 2021-05-14 at 11 57 00 AM" src="https://user-images.githubusercontent.com/13629122/118297138-c1dfa980-b4ab-11eb-9711-db2a3f040d80.png">


Play - ends at 12

<img width="815" alt="Screen Shot 2021-05-14 at 11 59 31 AM" src="https://user-images.githubusercontent.com/13629122/118297520-43373c00-b4ac-11eb-8017-1366d741f209.png">

If I go to the Frame for 12 and choose "set end", the number changes from 794 to 793 in the SignStream frame number display.

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-14 18:38
The problem is understood.  The solution is not.  We believe is related to known problem with the video player code, but to fix could take several days to properly correct.

**Comment by cneidle** [comment] 2021-05-24 16:55
Just to confirm that this is still a problem.   With latest 5/21 version of SignStream and a fresh copy of a file previously edited with version 3.3.5 (4-Ben-Deaf-Speech).

<img width="283" alt="Screen Shot 2021-05-24 at 12 52 07 PM" src="https://user-images.githubusercontent.com/13629122/119380547-dfbcc380-bc8e-11eb-8f34-2032de9dc2f8.png">

Go to end of selected utterance results in this:

<img width="643" alt="Screen Shot 2021-05-24 at 12 50 24 PM" src="https://user-images.githubusercontent.com/13629122/119380548-dfbcc380-bc8e-11eb-8edb-aba0890c4fcb.png">

But playing an utterance leaves off at an earlier frame of the video, although the frame number reported within SignStream is the same:

<img width="641" alt="Screen Shot 2021-05-24 at 12 50 15 PM" src="https://user-images.githubusercontent.com/13629122/119380549-e0555a00-bc8e-11eb-8454-0849b0b8a661.png">

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-28 17:04
This has been addressed at least as of 
SignStream4_4.1.0_pre_2021_05_27_1707_ac7cf550
SignStream3_3.7.0_pre_2021_05_27_1708_5e4dc83b

Closing.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-28 17:04 UTC
Labels: 4.1 release candidate, SignStream 3.7 - test-version-2, 5/21-latest-version-PM, Important: Need to confirm that this works
