### ISSUE TITLE
Saving with new handshapes 

### ISSUE THREAD

**Issue by aimeeaylward** [DCS-LCSR/SignStream3#140] opened 2017-06-08 00:59 UTC
On Rachel 55, Utterance 15, MARGARINE and NOT need new handshapes, but it seems I am unable to save and subsequently implement the new handshapes. The steps I would normally take to do are as follows:

1) Open the Morph-Phon Info box
2) Click CLEAR just below the Select Handhsapes button 
3) Click Select handhshapes
4) Insert appropriate handshapes in the Palette
5) Click Enter in the Palette box
6) Click Enter in the Morph-Phon Info box

When I click Enter, nothing happens. 
Is this something with the new version of sign stream?

**Comment by gregorydimitriadis** [comment] 2017-06-30 16:47
Hi @aimeeaylward 

I am unable to reproduce this issue - if possible and if time allows, can you please send a screenshot(s) of this issue occurring?

**Comment by cneidle** [comment] 2017-06-30 17:15
I just tried this and didn't have a problem.  A dialog box came up warning me that I  had to first add the sign to the Sign Bank (although the sign already existed in the Sign Bank). 

FWIW sometimes these dialog boxes that require a response from the user show up in very odd places where the user does not see them (including sometimes behind other windows).  I don't know if that was the problem for Aimee.  (This is especially true for the "Delete" confirmation, btw.)  So the user can think that the program is being non-responsive because the program is waiting for a response in that dialog box.

As for the Sign Bank check, does the check require the same handshapes?  This is a case where the handshapes are modified from what they would normally be, and thus what would be listed in the Sign Bank. But the gloss NOT was present in the Sign Bank. If handshape differences cause a problem with the match, that could be a problem, since there can be some variation in the handshapes..,

**Comment by cneidle** [comment] 2017-06-30 17:17
PS to Aimee - If you do go back to this file, please be sure to save it with a different name (e.g., "test" to the desktop), since we have already handed over this completed file to Augustine and it should not be saved with further modifications at this time.  Thanks.

**Comment by gregorydimitriadis** [comment] 2017-06-30 17:17
Handshape variations will not cause the sign bank to complain.

**Comment by cneidle** [comment] 2017-06-30 17:21
So, if the sign NOT had previously been entered in the Gloss window, and then I open the Morph-Phon window and change the handshapes, e.g., and then hit Enter, am I supposed to get an error message until I go the Sign Bank, search for NOT, and copy it back into Morph-Phon?  At what stage does the check happen to see whether the gloss is in the Sign Bank?

**Comment by gregorydimitriadis** [comment] 2017-06-30 17:23
It is determined solely by the string values for primary entry and variant. If those string labels are found in the sign bank, it will allow the user to proceed, regardless of the handshapes, other info, etc.

**Comment by cneidle** [comment] 2017-06-30 18:04
It seems to me that the match should be made solely on the basis of the entry/variant character string.  The primary entry is uniquely determined by the entry/variant, so checking on that is redundant at best.  And in cases where annotations have been done prior to the current Sign Bank functionalities having been implemented, the entry/variant is available in the Morph-Phon window, whereas the primary entry won't have been entered... FWIW.

**Comment by gregorydimitriadis** [comment] 2017-08-21 19:50
Related to #168

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-29 06:22
As of 

SignStream4_4.1.0_pre_2021_05_28_2110_7a9f7c09
SignStream3_3.7.0_pre_2021_05_28_2112_68341ef3

In Morph-phon, if of type lexical or number...."Enter" will only be clickable if Entry/Variant name is in the signbank.  If Enter is clickable, the signbank will still be checked prior to save.

Closing.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-29 06:22 UTC
Labels: complete, released
