### ISSUE TITLE
Start and end times not aligned for right and left hands

### ISSUE THREAD

**Issue by claireettlin** [DCS-LCSR/SignStream3#192] opened 2017-11-03 18:43 UTC
When trying to adjust handshape start and end times, only one utterance bar is adjusting. This is for utterance 4 Rachel 46
![screen shot 2017-11-03 at 2 40 58 pm](https://user-images.githubusercontent.com/32074197/32390585-55ac8baa-c0a5-11e7-89a0-ba46903dd479.png)
![screen shot 2017-11-03 at 2 41 03 pm](https://user-images.githubusercontent.com/32074197/32390586-56e87cc2-c0a5-11e7-90d5-2e88f1256c50.png)

Amanda & Alli

**Comment by claireettlin** [comment] 2017-11-03 18:47
But report seems to be an issue with a locking of the left and right hand alignments

**Comment by gregorydimitriadis** [comment] 2017-11-06 14:57
@claireettlin -- Is this gloss meant to be aligned, and it is not moving in alignment?

**Comment by cneidle** [comment] 2017-11-06 17:56
Sorry - Claire's comment doesn't make this clear - but this is NOT a bug.  Because file 46 had gotten totally corrupted and all but 2 sentences had disappeared, I restored a 2012 version of that file.  The default assumption for the older data seems to have been that the 2 hands were unlocked.  Once the user locks the two hands, they act in tandem, as they should.  So this issue can be closed, unless some other problem arises.

**Comment by gregorydimitriadis** [comment] 2017-11-06 18:32
Thanks Carol - closing..

**Closed as completed by gregorydimitriadis** 2017-11-06 18:32 UTC
