### ISSUE TITLE
Can't play selected utterances [w/199 - est. 6 hours]

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#233] opened 2018-06-19 14:25 UTC
I am reviewing Cory 114 and I am selecting various utterances to play (U11,U12,U13,etc) and instead of playing these utterances, Sign Stream only plays utterance one even when the utterances I want to view are highlighted in blue. If I click the play utterance button and get the actual utterance I want to play, it will and then it won't stop, continuing to play all the utterances instead of stopping at the end of the utterance I've selected. It will also go back to utterance one and play continuously all the utterances after U1. 

![screen shot 2018-06-19 at 10 20 51 am](https://user-images.githubusercontent.com/38887034/41603389-da556b20-73aa-11e8-902f-958c791619da.png)

![screen shot 2018-06-19 at 10 22 06 am](https://user-images.githubusercontent.com/38887034/41603394-dcc331c6-73aa-11e8-8dc2-9607450fe80f.png)

![screen shot 2018-06-19 at 10 22 17 am](https://user-images.githubusercontent.com/38887034/41603404-ded72396-73aa-11e8-8822-f011f3a6edf3.png)

**Comment by bugspotter33** [comment] 2018-06-19 14:33
Related issue in another Cory file 113 I try to select an utterance and instead of opening that single utterance, it gives me a view of multiple utterances at a time. When trying to click only on the utterance I want, nothing changes. 

![screen shot 2018-06-19 at 10 30 49 am](https://user-images.githubusercontent.com/38887034/41603996-23c64ef4-73ac-11e8-947d-7f4b79890da3.png)

I am also doing a search in this file and when a list of utterances show up after a search, I should be able to click on an utterance and it will appear down below. However, when U50 pops up in the search engine and I click on it, I am shown U20 instead.

![screen shot 2018-06-19 at 10 34 33 am](https://user-images.githubusercontent.com/38887034/41604165-95728874-73ac-11e8-9c1e-3b79024b2cea.png)

**Comment by cneidle** [comment] 2018-06-27 16:03
related to #199 ???

**Comment by gregorydimitriadis** [comment] 2018-08-17 19:07
@cneidle may I get the 114 collection file? Thanks

**Comment by gregorydimitriadis** [comment] 2018-08-17 19:27
I could not reproduce the case found in 113. I tried the case from 114 in other collections but could also not reproduce that.

**Comment by gregorydimitriadis** [comment] 2019-02-01 15:41
Update: we can reproduce the original case from 114, but not the one from 113. The 113 issue may be a zooming-related thing, so that clicking on an utterance might not bring you zoomed in properly enough to get the the proper one, but I can't confirm that.

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-07 16:05
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Both issues of play and search are believe corrected.

Closing.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-07 16:05 UTC
Labels: bug, complete, priority HIGH, released
