### ISSUE TITLE
Attempt to update to a prior version

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#485] opened 2022-01-15 20:01 UTC
A warning is appropriate, but this. text ??

<img width="566" alt="Screen Shot 2022-01-15 at 3 00 02 PM" src="https://user-images.githubusercontent.com/13629122/149636090-bf2aaa91-731d-4819-b1cd-46af4a907974.png">

**Comment by gregorydimitriadis** [comment] 2022-01-21 15:10
This appears to be a bug in the script.

**Comment by gregorydimitriadis** [comment] 2022-09-29 15:36
TODO: verify for actual version upgrades.

**Comment by gregorydimitriadis** [comment] 2022-09-29 15:51
Added to Todo milestone on zoom call with Chuck 2022-09-29

**Comment by gregorydimitriadis** [comment] 2022-12-16 16:27
Carol, regarding this issue: the reason the update script failed in this instance is because it was done from the test/pre-release version, and it is not meant to handle those strings (e.g. "3.3.7_pre_...."). While it might be possible to put in checks to mitigate this, since many operations in the script depend on the versions of SignStream implying certain (definite) things about the files inside, and these test releases being somewhat undefined in terms of their layout, it might mean invalid operations taking place. So we'd prefer to avoid that and leave it such that the update script is not meant to work with these test versions.

Separately, I have noticed other issues while I was testing this. Oftentimes I've seen errors on a 'sed' call looking for file 'SignStream3.app/Contents/Resources/info.txt' on versions where this file hadn't existed yet (I believe it's pre-3.3.6). I believe this is an issue with the current patch files which are downloaded as part of the update process, but I have not confirmed this yet. I intend to resolve this as part of this issue.

**Comment by cneidle** [comment] 2023-02-18 17:28
I made a copy of my SignStream test folder on my desktop so that I could try the update menu item.

This is what showed up in my terminal window:

<img width="559" alt="Screen Shot 2023-02-18 at 12 18 11 PM" src="https://user-images.githubusercontent.com/13629122/219879707-7bb1db9e-6ae4-4ad5-ae19-02c7dd8a9dde.png">

If I run the application in the original folder, this is what appears:

> Last login: Sat Feb 18 12:22:21 on ttys001
> carolneidle@Carols-MacBook-Pro ~ % /Users/carolneidle/Desktop/Out-of-the-way/SignStream3-for-testing-copy/Update.command --patch --install latest; exit; 
> 
> Starting Update Process for SignStream3
> 
> Finding patch version.
> No patches applied yet.
> Checking if new patches exist.
> Checking for new patches.
> No new patches exist.
> 
> 
> Attempting to update to the latest version.
> The latest version is currently 3.4.0.
> 
> Verifying the 3.4.0 Version of SignStream3 exists...
> It Exists.
> 
> Current SignStream3 Version: 3.4.1
> New SignStream3 Version: 3.4.0
> 
> The new version of SignStream3 is older than your current version.
> No Update available for SignStream3.
> Do you wish to downgrade this version? (Please answer "yes" or "no")
> no
> You answered "no".
> 
> If you want to update the SignBank, please run the command GetSignBank.command.
> 
> You can now close this window (click 'X', or press enter, to close).
> 
>

**Comment by cneidle** [comment] 2023-02-18 17:34
If I remove the space from the folder name, it works properly.
Changed from "SignStream3-for-testing copy" to "SignStream3-for-testing-copy"

**Comment by douglas-motto-at-rutgers** [comment] 2023-02-24 20:31
@gregorydimitriadis What Carol is describing is when a space is in the path name and the update is triggered from within SignStream.

All shell calls needs the full path (possibly other things) escaped.  This should occur for all script calls...SS update check, SS update, SB update....etc.

**Comment by gregorydimitriadis** [comment] 2023-02-28 17:10
@cneidle Will be looking into this - should be a simple fix from within the java code. But I'll see for sure.

**Comment by gregorydimitriadis** [comment] 2023-03-01 20:49
@cneidle @douglas-motto-at-rutgers spent some time trying to do this, but having more difficulty than anticipated. Pondering making this an explicit "known issue" in the readme for now.

**Comment by douglas-motto-at-rutgers** [comment] 2023-03-01 23:39
@gregorydimitriadis point me to code...this should be a quick fix.

**Comment by douglas-motto-at-rutgers** [comment] 2023-03-01 23:40
@gregorydimitriadis point me in an outside email.

**Comment by gregorydimitriadis** [comment] 2023-03-07 21:59
@cneidle I have a fix for when there is a space character in the filepaths. But on trying to "cover all bases" and testing the same thing with paths containing single quotes ( ' ) or double quotes ( " ) there are a variety of issues which come with that, which would probably take too long to address at the moment.

I would recommend we just make a known issue for there being those issues with single/double quotes in paths, and suggest users re-name their paths if possible.

**Comment by cneidle** [comment] 2023-03-07 22:07
Sounds very reasonable.

Thanks !!

**Comment by gregorydimitriadis** [comment] 2023-10-02 17:51
Spinning off previous comment:
https://github.com/DCS-LCSR/SignStream3/issues/691

Closing curent isue.

**Comment by gregorydimitriadis** [comment] 2023-10-02 17:51
Released in 3.4.1

**Closed as completed** 2023-10-02 17:51 UTC
Labels: bug, released, 3.3.7-pre Jan 2022, severity HIGH, usability concern
