### ISSUE TITLE
Nonmanual double click menu missing

### ISSUE THREAD

**Issue by carlyzx9** [DCS-LCSR/SignStream3#97] opened 2016-07-12 21:40 UTC
Originally, you could double click on an existing nonmanual event and it would open a drop-down menu of all label options for that event. This menu no longer appears, meaning we have to delete the event and recreate it, which leaves concerns about accuracy of exact start and endpoints. Now, however, nothing happens when double clicking an event. 

When you create a new event, the menu pops up as it always has, but you cannot access it again after creating the event.

![screen shot 2016-07-12 at 5 35 51 pm](https://cloud.githubusercontent.com/assets/19909811/16784523/212ed256-4857-11e6-8a7d-7487399a59c9.png)

Also, when changing screens, the NM menu remains visible (such as right now when switching from the SignStream window to the GitHub window)
![screen shot 2016-07-12 at 5 37 07 pm](https://cloud.githubusercontent.com/assets/19909811/16784561/47587b76-4857-11e6-8673-a79e19ee748f.png)

It makes no difference what field is being used and is present in all files we have tested.

**Comment by gregorydimitriadis** [comment] 2016-07-26 13:29
Turns out this bug is only occurring as a result of some half-done work for bug #85 so I'm going to link this here. When that bug is fixed soon, then I will automatically close this one as well.

**Comment by geograil** [comment] 2016-07-26 18:57
The menu not showing up has been fixed in the patch; it does show up when you double click an existing non-manual event. 

As you've indicated would be the case due to the remaining work on bug 85, the menu remaining visible when switching windows is indeed still happening: 

![screen shot 2016-07-26 at 2 56 34 pm](https://cloud.githubusercontent.com/assets/19953651/17151313/34989030-5341-11e6-97a7-a5cba35c830e.png)

**Comment by gregorydimitriadis** [comment] 2016-09-29 14:03
@geograil Hi Graham, can you please check whether this bug is still occurring with the latest version release? 
https://www.dropbox.com/s/jyxue2l5ck0t9ek/signstream_uat.zip?dl=0

**Comment by hammondcl** [comment] 2016-10-03 15:14
Yes, this is still happening in the latest version.

**Comment by gregorydimitriadis** [comment] 2017-01-25 15:35
Along with issue #101, after the changes made for Sprint 20, I am unable to reproduce this issue, so I will mark this as complete. If the issue re-appears, post a comment here noting this and I'll take another look into it.

**Comment by hammondcl** [comment] 2017-01-25 16:21
This appears to remain an issue. 

![screen shot 2017-01-25 at 11 20 47 am](https://cloud.githubusercontent.com/assets/15836242/22298975/65e98b50-e2f0-11e6-8721-4a86271b6572.png)

**Comment by hammondcl** [comment] 2017-02-15 16:12
This is resolved by Sprint 21

**Closed as completed** 2017-02-15 18:33 UTC
Labels: bug, complete
