### ISSUE TITLE
problem opening database view/viewing specific utterances

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#477] opened 2021-07-01 19:56 UTC
Working in SS file PF18_V03 Takes 2-3 tries to select the utterance you want in SS. The first several tries the program stays on utterance 1. I have to keep selecting "back to database view" until I can select an utterance I want. The view changes from seeing all the utterances to just seeing U1 and that's when I know that I can go in and select the desired utterance. 

In the following screenshots I've selected U25 as my desired utterance when first opening SS. SS still takes me to U1 even though U25 is highlighted. 

![Screen Shot 2021-07-01 at 3 52 59 PM](https://user-images.githubusercontent.com/38887034/124182373-9d478d00-da6b-11eb-8f2d-381fb3086b91.png)

![Screen Shot 2021-07-01 at 3 53 07 PM](https://user-images.githubusercontent.com/38887034/124182389-a173aa80-da6b-11eb-8e4d-2d1ce552af52.png)

![Screen Shot 2021-07-01 at 3 53 20 PM](https://user-images.githubusercontent.com/38887034/124182404-a6385e80-da6b-11eb-9fa1-15faedbb693f.png)

![Screen Shot 2021-07-01 at 3 53 32 PM](https://user-images.githubusercontent.com/38887034/124182414-a9cbe580-da6b-11eb-8c3e-58a889ee1d36.png)

**Comment by gregorydimitriadis** [comment] 2021-10-15 17:09
@gregdimi note to self: test with PF18_V03 collection again to verify

**Comment by gregorydimitriadis** [comment] 2022-09-29 15:50
Added to Todo milestone on zoom call with Chuck 2022-09-29

**Comment by gregorydimitriadis** [comment] 2022-12-16 16:29
Carol - I haven't looked at this one yet recently, but at the time I do - in the circumstance I'm unable to reproduce the described issue (say, either with the specified collection file or otherwise) would we be fine moving this out of the 'severe' category?

**Comment by cneidle** [comment] 2022-12-16 16:32
Hi Greg,

YES.  Thanks.  Fine to close this until such time as it should be observed again.

Thanks so much !!

**Comment by cneidle** [comment] 2023-02-06 18:50
in my prior experience, this problem was resolved by changing the zoom even by a little bit.

**Comment by douglas-motto-at-rutgers** [comment] 2023-02-06 21:00
Just some information to add to the issue for future reference, if in fact the issue is related to the "zoom".  The image included above doesn't include the "L"/"U" lock/unlock toggle button next to the zoom slider.  Going off non-pre release versions, that would mean the picture is from version 3.3.6 or earlier.  There may also have been some later pre 3.3.7 versions with this look.  I believe these versions do NOT include the completely rewritten zoom code that's now in the later versions and hopefully that solved the original problem.

**Comment by cneidle** [comment] 2023-02-07 17:09
The original bug report was from July 1, 2021; Indya was editing one of our older files, using 3.3.5 most likely.

**Comment by gregorydimitriadis** [comment] 2023-02-07 21:52
@cneidle shall we close this?

**Comment by cneidle** [comment] 2023-02-07 23:03
Yes.  suggest closing until such time as this should recur, if it does...  thanks.

**Closed as completed** 2023-02-07 23:03 UTC
Labels: complete, cannot reproduce, usability concern
