### ISSUE TITLE
Redirecting Utterances

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#219] opened 2018-05-25 16:25 UTC
I'm not sure if this is a bug or if maybe it is because of how close the utterances are but I am working on file 82 of the Rachel and Jonathan dialog and I am noticing that every time I select an utterance from the database view, I am shown/redirected to data from the previous utterance. The utterance before is highlighted in blue on the left hand side where you can see all the glosses and then the utterance before that and after the highlighted utterance are in gray. It's like the program isn't sure which utterance I'm actually referring to. If I then select the utterance I actually want which is what's in gray, I am directed to it's exact data but I can't seem to do this from the main data base view. I have attached screenshots. In these screenshots I want to open U28, U27 is highlighted in blue and that's the data that I am shown, while U26 and U28 are in gray on the left hand side. If I select U28 on the left hand side( the utterance I wanted to begin with) then the correct data appears. This is weird because the green line that tells where you are in the data is lined up at U27 when what I've selected is U28. This situation occurs throughout the file it and it does not matter which utterance is selected. 

![screen shot 2018-05-25 at 12 16 06 pm](https://user-images.githubusercontent.com/38887034/40555240-69120830-6016-11e8-92c4-b49842890b27.png)

![screen shot 2018-05-25 at 12 16 22 pm](https://user-images.githubusercontent.com/38887034/40555249-731e6616-6016-11e8-9636-7148411a666b.png)

![screen shot 2018-05-25 at 12 18 18 pm](https://user-images.githubusercontent.com/38887034/40555260-7cabee24-6016-11e8-8c41-e6409cd42411.png)

**Comment by cneidle** [comment] 2018-05-25 16:32
I have now seen this with my own two eyes…

It happens frequently but not always.  

The selected utterance is shown as n-1 relative to having clicked on utterance n.

Carol

**Comment by gregorydimitriadis** [comment] 2018-06-05 19:41
This was reproducible using this collection file.

**Comment by travisnguyen** [comment] 2018-11-29 19:42
This seems to be resolved in version 3.1.2.

**Closed as completed** 2018-11-30 15:28 UTC
Labels: bug, complete, priority HIGH, released
