### ISSUE TITLE
Sign bank gloss did not appear

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#627] opened 2023-01-28 03:41 UTC
When trying to enter the handshapes of a gloss (part:indef) the examples in the signbank to watch the videos of the utterance or "insert all data" does not appear once the gloss has been clicked  on. The bottom stays gray/blank. 

![Screen Shot 2023-01-27 at 7 37 22 PM](https://user-images.githubusercontent.com/38887034/215240397-01de535e-d209-4d6e-a118-25b31306922f.png)

**Comment by cneidle** [comment] 2023-01-28 03:45
Hi Indya,

Are you clicking on the top one, “part:indef”?

It’s working for me…

You don’t want to click on a compound part (something that starts or
ends with * ).

Thanks, Carol

**Comment by bugspotter33** [comment] 2023-01-28 03:47
Yes I am selecting the first one it is not working this is in U30 forgot to specify which utterance.

**Comment by cneidle** [comment] 2023-01-28 03:51
Still works for me

**Comment by cneidle** [comment] 2023-01-28 03:57
I restarted SS twice. The third time I was able to add the handshapes
manually. I just tried again and after waiting a while the insert all data
option appears.

Indya

**Comment by cneidle** [comment] 2023-01-28 04:09
Perhaps the issue is a slow network connection.

C>

**Comment by gregorydimitriadis** [comment] 2023-01-30 15:10
There's no indication of an error in the out.txt file I received. Marking as not reproducible until it happens again.

**Comment by cneidle** [comment] 2023-04-16 21:16
This has been resolved in the latest Sign Bank that is about to be released.

**Closed as completed by cneidle** 2023-04-16 21:16 UTC
Labels: cannot reproduce
