### ISSUE TITLE
Reattaching macro unit caused file to become unworkable (Cory 108)

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#160] opened 2017-07-24 15:18 UTC
Carol sent some screenshots of Cory 108 and I wanted to see if I also noticed the issue she was discussing. I opened the file, tried to open the utterance, but it would not. I noticed that the macro unit was incorrectly attached, so I removed the one video that was attached and reattached all four videos correctly. Clicking "Confirm Selections" to display the videos caused this to occur: 

![screen shot 2017-07-24 at 10 54 21 am](https://user-images.githubusercontent.com/15836242/28529793-778d8da0-705f-11e7-93af-8d43fa47106d.png)

Upon quitting and reopening the program, the utterances opened correctly.

**Comment by gregorydimitriadis** [comment] 2017-08-21 17:01
@hammondcl, @cneidle I believe this was due to the zoom changing after videos are re-attached to the collection. If this is possible to reproduce - could you try it again and then change the zoom to something more visible? I believe this should work.

**Comment by cneidle** [comment] 2017-08-21 21:49
I agree that this is likely due to the zoom.  I don’t think this is a continuing problem.
thanks,
 Carol

**Comment by gregorydimitriadis** [comment] 2017-08-22 13:15
@cneidle - Worth closing, or just prioritizing for later?

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-07 03:26
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Fixed...reattaching videos seem to work and display properly.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-07 03:26 UTC
Labels: question
