### ISSUE TITLE
Wrong Morph-Info [w/232 - est. 15 hours]

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#216] opened 2018-05-11 17:27 UTC
I am working on file 82 of the Rachel/Jonathan data utterance 29 (U29) and I have been noticing some strange things happening with the morp-info. I am going through all the glosses for Jonathan and there was a gloss that is one-handed and has a different start and end shape. I selected all this information in the morp-info window and saved the work. I then went back into the morp-info of the gloss and the information was wrong. This isn't the only gloss that this has happened with. I've seen one gloss that looked fine and then when I clicked on the morph-info there wasn't any information inside. I am going through all glosses now to make sure the morph-info corresponds to what is being shown in the temporal partition. 

I've attached a screenshot of the wrong information for the sign (3)INJECT. (the drop down selection should say different start and end hs)
![screen shot 2018-05-11 at 1 21 17 pm](https://user-images.githubusercontent.com/38887034/39937807-e9ff5478-551e-11e8-9147-b1ba79c18f79.png)

**Comment by bugspotter33** [comment] 2018-05-11 18:14
This is another example of a sign that should only be a lexical sign and not glossed as a name sign.


![screen shot 2018-05-11 at 2 12 33 pm](https://user-images.githubusercontent.com/38887034/39939863-95cf52d4-5525-11e8-9d7f-2303422a608c.png)

**Comment by cneidle** [comment] 2018-05-11 19:04
Just a quick comment:  So Indya had the sign entered correctly, but when she came back to it, the "Name Sign" box appeared to be checked, although she hadn't checked it.  This was not an isolated case; she found this happening several times. Errors like this are very hard to catch, since they aren't visible except in the Morph-Phon window. So, these errors may be affecting other files as well. 

When we load the data into the DAI, the search results will be totally messed up if these categorizations are not saved correctly...   FWIW.  So far at least, with the files that had been uploaded as of about 2 months ago, there are no errors showing up in the DAI search for "name signs".  But we have a lot of recent data that we are on the verge of uploading.  So when we do, I'll check to see if there are any errors of this type.    

Thanks.

**Comment by bugspotter33** [comment] 2018-05-11 19:13
Rachel file 82 U14. Another issue I am having is trying to enter information in the morph-info window about a number but not having the drop down menu section to select that the handshape of the number differs. One thing I am noticing is that when I select the number selection at the top of the morph-info window and then select one handed for the sign, my option to select whether or not the hand shapes are similar or different disappears. 

![screen shot 2018-05-11 at 3 10 32 pm](https://user-images.githubusercontent.com/38887034/39942547-c54e4fc6-552d-11e8-9f42-4025cbfa0ade.png)

**Comment by gregorydimitriadis** [comment] 2018-05-25 15:17
On the initial issue, of the wrong macro unit screen, my hunch would be that it is just the display part (i.e. the frontend) which is in error, and not the underlying data from which it is generated. I am not sure, though - can you please attach the collection file here?

On the second thing, having to do with not seeing the drop down when selecting number, that appears to definitely be a bug.

**Comment by cneidle** [comment] 2018-05-25 15:22
Hi Greg,

I’m attaching the file here.

Thanks,
  Carol

**Comment by gregorydimitriadis** [comment] 2018-05-25 15:48
Hi Carol,


Did it get attached? I don't see it..


Might have to do it through github


-Greg

________________________________

**Comment by cneidle** [comment] 2018-05-25 15:50
Hi - Yes I did attach it.



Github does not accept this filetype.

I can try making a zip of it and resending…

Thanks,
 Carol

**Comment by cneidle** [comment] 2018-05-25 15:53
Here’s a zip of it

**Comment by gregorydimitriadis** [comment] 2018-05-30 20:13
@bugspotter33 I can't seem to reproduce the initial case - with gloss (3)INJECT.

On opening your collection file, I can open that gloss and see the proper values - "Diff't START/END hs" shows up as it should.

Do you have any other glosses which you can point to and reliably see the error? If possible provide a series of steps which you did before the error happened.

**Comment by bugspotter33** [comment] 2018-05-31 16:58
Jonathan file 82 U4 and U5 both have a name sign glossed as ns-BRUCE. In U4 I don't see the option to change the handshapes(if a change was needed) in the drop down menu yet in U5 the drop down menu is shown (see screen shots below)

![screen shot 2018-05-31 at 12 54 58 pm](https://user-images.githubusercontent.com/38887034/40796181-38a7f32e-64d2-11e8-9bde-6254aad047f1.png)

![screen shot 2018-05-31 at 12 55 56 pm](https://user-images.githubusercontent.com/38887034/40796184-3bde8c92-64d2-11e8-8c39-0f63ee0ab078.png)

**Comment by bugspotter33** [comment] 2018-05-31 17:33
What I am noticing thus far...

With regards to the drop down menu disappearing, I found that if one gloss has this issue when you open the morp-info window, then the glosses to follow will also have the same issue when you open their morp-info windows. However when clicking on a gloss that may be two handed, it seems to break the cycle as the information of the two handed gloss appears fine in the morp-info window. (see screen shots below) This occurred in U7 of the Jonathan data in file 82 the issue started at the gloss (1h)FINISH and ended when I opened the gloss 5"you see" (Similar issue occurring at U33 and U38 starting with the gloss #BUT and ending at U40 with the gloss REALLY)

![screen shot 2018-05-31 at 1 02 46 pm](https://user-images.githubusercontent.com/38887034/40797608-c8970e62-64d6-11e8-92fc-9b4741d40452.png)

![screen shot 2018-05-31 at 1 03 11 pm](https://user-images.githubusercontent.com/38887034/40797615-d0cfc4f2-64d6-11e8-9aa5-46ddab7b6154.png)
![screen shot 2018-05-31 at 1 31 00 pm](https://user-images.githubusercontent.com/38887034/40797627-e3973b56-64d6-11e8-908c-41235434eca2.png)


I have also found, in U11 of file 82 of the Jonathan data, a one handed gloss that has a different start/end handshape that was saved as such, yet has morph-info that says otherwise. I have changed the data to correct the issue however I have done this in the past and clearly the changes aren't being saved. I am going to continue to go through the file to see if I can find anymore examples. (similar issue same file U26 ns-BOB HOFFMEISTER and U29 #BUT)

![screen shot 2018-05-31 at 1 18 45 pm](https://user-images.githubusercontent.com/38887034/40797665-00cd8266-64d7-11e8-982c-1c2a55443e02.png)
@ 



U38 #ED this two handed sign should have two drop down menus. The second one that allows me to mark a difference in the start and end handshape is missing (I have also seen this issue occur in a different file I am currently working on Cory file 113 U61)

![screen shot 2018-05-31 at 2 06 17 pm](https://user-images.githubusercontent.com/38887034/40800475-878d6dbe-64de-11e8-9894-420e54d8f036.png)

U40 the gloss 5"sigh" is a gesture but is shown as lexical in the morph-info window

![screen shot 2018-05-31 at 2 36 25 pm](https://user-images.githubusercontent.com/38887034/40801205-5a516876-64e0-11e8-908d-18e21338da80.png)

**Comment by cneidle** [comment] 2018-05-31 18:40
Just to clarify the above:  The issue is not the ability to reselect handshapes.  It is the problem with the menus that ought to be visible (and that ought to display the previously encoded information correctly) for the relationship between start and end handshapes, and the relationship between the handshapes on the two hands for 2-handed signs.  Thanks.

**Comment by bugspotter33** [comment] 2018-06-01 18:52
Today I am going through all the Rachel data to see if there are any bugs that can be reproduced and I've found one that I've mentioned before. The gloss is TWELVE which should be labeled as a number in the morph-info window, however it was marked as a lexical sign when I opened the morph-info window. Everything else was correct. When I tried to click on the number button the drop down menu to select whether or not the handshapes are the same or different, disappeared. I am in file 82 Rachel U8. I have saved it the correct way now and hopefully the changes will stay saved. 

![screen shot 2018-06-01 at 2 47 12 pm](https://user-images.githubusercontent.com/38887034/40858134-558ca730-65ab-11e8-9b0c-0183893f2cab.png)


![screen shot 2018-06-01 at 2 47 31 pm](https://user-images.githubusercontent.com/38887034/40858139-5823fd0e-65ab-11e8-83ad-64b73dbd7b2c.png)

**Comment by cneidle** [comment] 2018-08-04 19:02
moved this a tiny bit higher in the priority list

**Comment by gregorydimitriadis** [comment] 2018-09-20 17:42
There's some logic in the code at play from previous issues which may be responsible for some of the things reported here. For instance:

* clicking fingerspelled, loan, or number results in:
  * auto-select onehanded
  * set passive base arm unchecked
  * set all three comoboxes (sameDifStartEnd, sameDifStartEndLeft, sameDifStartEndRight) invisible
* clicking gesture results in:
  * all of the above, plus set marked hands unchecked
* clicking lexical or classifier results in:
  * auto-select twohanded
  * set visible the sameDifStartEnd combobox
  * marked hands unchecked
  * passive base arm unchecked

**Comment by gregorydimitriadis** [comment] 2018-09-20 19:52
Can't reproduce the "same start/end hs" combobox not showing up for one-handed signs.

**Comment by gregorydimitriadis** [comment] 2018-09-20 20:26
@cneidle This is relevant to both this issue and was also mentioned in #228:

There is some logic in the morph phon window code which, upon opening the MorphPhon window, if the gloss was not saved to the xml with anything for SIGN (lexical/classifier/number/fingerspelled, etc) then it makes an 'educated guess' based on the gloss name as to what should be automatically selected for that sign type.

It does this by what's known as regex pattern matching on the gloss name string. For instance, the one mentioned in #228 is about classifiers, which gets noticed via this regex string:
```String classifierPattern = "(!)?(neu:|([a-z_1-3][p:]))?([(1h)][(2h)][(2h)alt.])?(ns-)?((CL)|(DCL)|(LCL)|(SCL)|(BCL)|(BPCL)|(PCL)|(ICL)){1}(.*)?"; ```

Anything starting with CL/DCL/LCL, etc (**if it was not saved properly to the xml**) would get marked as classifier upon re-opening the MorphPhon. So it would only happen occasionally. I can see no reason why the sign type would not have gotten saved properly for these signs, but that appears to be the case, at least for the above.

This code, in general, seems dangerous if everything is meant to be marked manually by users. So, I'd recommend taking out all of this 'educated guess' code - unless you see a reason to keep it in.

**Comment by cneidle** [comment] 2018-09-22 21:00
Hi,

Passive base arm should always be unchecked by default.
Same for marked number of hands.

The other default settings that I’ve bolded below are correct.

Once the user changes the default settings, that should remain, of course.

I would think that a gesture should also have the same vs. different start/end handshape box checked,
and if the user makes it two-handed, then the box about the relationship between the two hands
should also appear.

Thanks,
 Carol

**Comment by cneidle** [comment] 2018-09-22 21:10
This is a comment about the regex pattern matching.  It is great if the type of sign can be predicted (and assigned by default when the user opens the Morph-Phon window for the first time) from the characters in the sign, as is apparently being done, if I understand correctly.

The problem, I think, is that we want exact word match for the string of upper case letters = 
CL  DCL  LCL etc.  (possibly followed by other characters that are not upper case letters).
It should not be anything starting with CL which would match with, e.g., "CLASS" - where the
"CL" is not functioning as a sign-type prefix in that case.  This is the error that was detected.

Again, once the default value is changed, i.e., once the user selects a sign type, then the
default values should not override what was manually set.

(Not sure I have completely understood what is actually happening.)

**Comment by gregorydimitriadis** [comment] 2018-10-11 19:29
@cneidle once the default value is changed, the value does indeed remain (as far as I've seen). But there are some glosses which were not saved with any default value - I'm not entirely sure the steps which preceded that happening, as it shouldn't be possible (given what a user can do in the app).

Which colleciton/gloss was the detected "CL" type error?

**Comment by cneidle** [comment] 2018-10-12 17:26
Hi Greg,  Wherever that CL error had been found, we manually corrected it.  HOWEVER, the issue is that the data entry process selects a default type from the gloss, which is EXTREMELY useful, and it erroneously thinks that CLASS is a classifier, cf. 
![screen shot 2018-10-12 at 1 23 29 pm](https://user-images.githubusercontent.com/13629122/46884190-406e9900-ce22-11e8-83a0-0a079900645a.png)

I'll email you this file, but you can reproduce this by typing in, e.g., "CLASS" in the gloss field and then going to the morph-phon window. 

Thanks.

**Comment by travisnguyen** [comment] 2018-11-29 19:41
Discrepancy: This bug has been noted as fixed in the release notes for 3.1.2, but has only been partially addressed.

**Comment by gregorydimitriadis** [comment] 2019-02-27 19:22
@cneidle @travisnguyen what is the current state of this issue?

**Comment by gregorydimitriadis** [comment] 2019-03-27 18:48
Hi @travisnguyen just checking in again - do you remember which part of this issue is not addressed?

**Comment by travisnguyen** [comment] 2019-03-27 21:51
@gregorydimitriadis My last comment was about a discrepancy between how the bug fix was described in the README.txt for version 3.1.2 ("fixed") and in the e-mail that Carol and I received that included a list of bug fixes in version 3.1.2 ("partially fixed"). I haven't looked at this bug in detail, but if the issue is resolved, feel free to mark it as complete.

**Comment by gregorydimitriadis** [comment] 2019-03-28 13:33
Ah I see - thanks. Indeed, I noted about the partial fix because I attempted to address many of the concerns from this issue but don't have 100% every issue is resolved. Maybe we can leave this issue and #232 open as placeholders in case the issues crop up again.

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-07 14:42
This may be corrected as of
SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

But need to reverify requirements and implementation.

So leaving open for now.

**Comment by cneidle** [comment] 2021-10-15 23:08
fixed ??

**Comment by gregorydimitriadis** [comment] 2022-09-22 19:37
Should be fixed - closing for now.

**Closed as completed by gregorydimitriadis** 2022-09-22 19:37 UTC
Labels: bug, enhancement, complete, priority HIGH, released, PRI 1
