### ISSUE TITLE
File is blank when opening

### ISSUE THREAD

**Issue by geograil** [DCS-LCSR/SignStream3#87] opened 2016-06-21 13:56 UTC
File: Jonathan 96

I was trying to open the file to reference something and when I tried to open it, the whole thing is blank. You can tell that the program did try to open it, but nothing shows up. 

My steps: 

I opened SignStream, clicked Collection -> Open, went into the CURRENT folder and clicked the file like usual. 

![screen shot 2016-06-21 at 9 50 06 am](https://cloud.githubusercontent.com/assets/19953651/16231848/0c8d446c-3796-11e6-8824-f3bb2bcd69aa.png)

It then presented the screen as if it opened the file, but there is nothing there. I tried to zoom the view in/out a little bit as I was told that sometimes you have to do that, but there was still nothing. 

![screen shot 2016-06-21 at 9 44 18 am](https://cloud.githubusercontent.com/assets/19953651/16231883/3d731b24-3796-11e6-8464-3161d99f5dc9.png)

Other files for both Jonathan and Rachel are opening just fine, so I'm not sure whether it is a bug with SS and this file or if the file is the problem.

**Comment by hammondcl** [comment] 2016-06-21 14:00
Graham-
I believe we've had issues with this file before. Go to the Excel spreadsheet on the desktop entitled "Files to work on" (top left of desktop) and scroll down until you see Jonathan 96 and check the Notes column.

**Comment by geograil** [comment] 2016-06-21 14:09
Ah, I do indeed see a note about it not having a macro unit attached. Carol and I just looked through it and found that out as well. I'll double check all the notes before trying to look at anything else for references and such.

**Comment by gregorydimitriadis** [comment] 2016-06-21 14:13
Thanks Chelsea.

Graham, mind if I close this ticket out?

**Comment by geograil** [comment] 2016-06-21 14:15
Greg, that's fine. Sorry for the confusion.

**Comment by cneidle** [comment] 2016-06-21 14:17
Hi Greg,

Thanks - this does not seem, then, to be a general problem,
but rather a problem with this specific file — which hopefully can
at some point be investigated and repaired…

So perhaps leave this as an issue, but in relation to this specific
file ?   I believe that there was quite a lot of data that had been
coded but that is now, for some unknown reason, unaccessible 
in this file...

thanks very much!

best,
 Carol

**Comment by gregorydimitriadis** [comment] 2016-06-21 14:19
Carol,
Sure I'll leave this open as a marker for that file to be investigated at some point.

**Comment by gregorydimitriadis** [comment] 2017-02-01 15:18
@geograil I cannot reproduce the issue with this file on my end, neither in my development environment nor while testing using a zipped Signstream package.

I open up the collection, and immediately see the utterances. The box to select annotator appears, and I add my name. Then I'm in the main Signstream database view window, but with the videos not yet attached. I go to edit macro unit and select the videos. (The names of the videos in the collection had "for-ss3" appending to them all, but the videos I've found for 0096 did not have the "for-ss3," which could mean they were of a different type - not sure.) Once I select all four videos and hit enter out of the 'edit macro unit' screen, everything now looks normal and I can use Signstream perfectly.

Graham - can you verify this issue with the file is still occurring for you?

**Comment by hammondcl** [comment] 2017-02-01 16:14
I'm investigating this now and it seems that whatever issue once existed has been resolved. Opening the file (Collection --> Open --> CURRENT --> Jonathan 96) opens it correctly, with all utterances present and accessible and all videos in the macro unit appearing correctly.

**Comment by gregorydimitriadis** [comment] 2017-02-02 14:49
Thanks @hammondcl - I'll mark this as 'complete' for now then.

**Comment by hammondcl** [comment] 2017-02-15 16:28
All appears to be fine with this file now

**Closed as completed** 2017-02-15 18:34 UTC
Labels: bug, complete
