### ISSUE TITLE
Overlap allowed (when it shouldn't be) when user adjusts start frame of gloss [est. 7. hours]

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#242] opened 2018-07-22 16:47 UTC
I'm working on file 107, U 20.  I attempted to adjust the start point of COOK.

When I tried to move the start to a point prior to the end of the preceding sign, I did get a warning dialog box, but succeeded in doing this by ignoring that box.  This should not be allowed to happen.

<img width="363" alt="screen shot 2018-07-22 at 12 46 02 pm" src="https://user-images.githubusercontent.com/13629122/43047929-5bac461e-8dad-11e8-936b-ae600b46d9d1.png">

<img width="335" alt="screen shot 2018-07-22 at 12 44 12 pm" src="https://user-images.githubusercontent.com/13629122/43047932-61eb7af4-8dad-11e8-9704-18cc63bc1626.png">

**Comment by cneidle** [comment] 2018-07-22 16:49
There is also an issue in locking and unlocking the two hands.  Once the hands have been unlocked and then locked again, they still behave as unlocked with respect to the display of handshapes.

**Comment by cneidle** [comment] 2018-07-22 19:30
A related issue:  I get this warning when I SHOULDN'T - although again, the warning does not prevent me from increasing the endpoint in this case by 1 frame.  (There is nothing to the right, so no overlap involved at all.)

This is file 107 - U 64.

<img width="492" alt="screen shot 2018-07-22 at 3 28 34 pm" src="https://user-images.githubusercontent.com/13629122/43049349-2cea9c42-8dc4-11e8-82c1-a1e03b1fb6dc.png">


<img width="649" alt="screen shot 2018-07-22 at 3 28 43 pm" src="https://user-images.githubusercontent.com/13629122/43049351-311ecff4-8dc4-11e8-87c6-956993c63f68.png">

**Comment by cneidle** [comment] 2018-08-04 19:37
have increased priority level

**Comment by gregorydimitriadis** [comment] 2018-08-17 21:13
Reproduced and debugging

**Comment by gregorydimitriadis** [comment] 2018-08-31 14:28
First case is fixed. Working on second case (whoa and REFUSE)

@cneidle is this accurate to say:

That if a gloss has a dom and nondom aspect, AND it is marked as locked left-right, then *by definition* the dom and nondom parts both have to have the same start/end times? So in the picture (and I can reproduce this when testing as well) with the blue diamonds showing for "whoa" it's thinking that it's locked, when it is by definition not locked (because nomdom has different start/end times) - which is ultimately the error? I'm seeing that if SignStream correctly interpreted this gloss as unlocked the issue would go away.

**Comment by cneidle** [comment] 2018-08-31 17:50
Yes, that sounds right to me.

Thanks,
 Carol

**Comment by travisnguyen** [comment] 2018-11-29 19:28
The second case (whoa and REFUSE) seems to be resolved in version 3.1.2.

**Closed as completed** 2018-11-30 15:25 UTC
Labels: bug, complete, priority HIGH, released
