### ISSUE TITLE
For the wishlist... 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#303] opened 2019-12-27 19:13 UTC
Have been wishing for this for a long time:  When you do a "save as" the name of the current file should show up by default.   The user should not have to retype the whole filename...   Thanks!

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-07 19:54
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Done

Closing.

**Comment by cneidle** [comment] 2021-05-16 16:21
This is no longer working properly.  What should appear as the default for saving the file is the current file name; what shows up is the name of the containing folder.

<img width="467" alt="Screen Shot 2021-05-16 at 12 18 09 PM" src="https://user-images.githubusercontent.com/13629122/118404483-18322100-b641-11eb-9ca4-33785718808c.png">

Note that this HAD been working in recent versions (at least up to 3.3.5), and I have been using this feature a lot :-)

**Comment by douglas-motto-at-rutgers** [comment] 2021-10-16 00:44
Believe this is fixed....but needs to be re-tested.

Leaving Open.

**Comment by gregorydimitriadis** [comment] 2021-10-21 15:21
Can not reproduce in current/pending version. Assuming fixed for next release.

**Comment by gregorydimitriadis** [comment] 2022-04-19 13:59
Still cannot reproduce in versions 3.4.0+ - closing.

**Closed as completed by gregorydimitriadis** 2022-04-19 13:59 UTC
Labels: enhancement, priority LOW, v3.7 - 5pm on Friday May 14, PRI 1
