### ISSUE TITLE
Trying to open a new file while in utterance view does not open new file and makes it impossible to work with current file

### ISSUE THREAD

**Issue by geograil** [DCS-LCSR/SignStream3#88] opened 2016-06-21 14:52 UTC
When you're looking in an utterance and you go to open a new file, it doesn't open the new file and it makes it impossible to continue working with the original file as well. It closes the videos you were working in (as you would expect), but then it just makes the utterance view of the current file have issues with the zoom and isolating specific utterances. 

Starting spot in an utterance: 

![screen shot 2016-06-21 at 10 26 00 am](https://cloud.githubusercontent.com/assets/19953651/16233267/cae02a42-379b-11e6-85a3-7a1c91d4639e.png)

You click collection -> open. It closes the videos, makes the utterance pane brown/yellow, and gives you the dialog box to pick the new file:

![screen shot 2016-06-21 at 10 29 20 am](https://cloud.githubusercontent.com/assets/19953651/16233304/e572a79a-379b-11e6-8dc3-d9f5ce8f310e.png)

When you click the file and click open, this screen shows up: 

![screen shot 2016-06-21 at 10 30 22 am](https://cloud.githubusercontent.com/assets/19953651/16233327/f818d2ac-379b-11e6-8080-30c84ef2814a.png)

It is the original file with all of the utterances smashed into the same view pane and a group of them are automatically selected together in the left sidebar. I tried to click on just one utterance on the left sidebar to see if that was the issue, but it just re-selected the group. I then thought the zoom level may be the issue, but when you zoom it all the way in, you can see the coding for one utterance but can't click into it to select time points or glosses. It also still has a group of two selected on the left sidebar. 

![screen shot 2016-06-21 at 10 30 59 am](https://cloud.githubusercontent.com/assets/19953651/16233549/cfd3bcb6-379c-11e6-8517-c1d7e2d93949.png)

It works normally when starting in this view:

![screen shot 2016-06-21 at 10 50 09 am](https://cloud.githubusercontent.com/assets/19953651/16233974/0d7cca5c-379e-11e6-93b8-8ebf2640e154.png)

Right now, I just quit out of SignStream and restart it to open a new file as a workaround.

**Comment by hammondcl** [comment] 2016-09-28 17:24
Now instead of opening unusable utterances, you are prompted to save the changes you have made to the existing file. I did not make changes, so I clicked "Don't Save" and nothing happened. The videos closed as soon as I clicked "Collection" --> "Open...". I tried again and then selected "Save" and then everything froze and the spinning rainbow wheel appeared. I let it go for a few minutes to see what would happen, but there was no change. Eventually, I force quit the program.

**Comment by hammondcl** [comment] 2017-02-08 18:26
Today, we tried to open Rachel 45 from Rachel 43 and this is the screen that occurred. The macro view in the left panel says "Rachel 45", but the title at the top of the screen reads "Rachel 43" 
![screen shot 2017-02-08 at 1 06 23 pm](https://cloud.githubusercontent.com/assets/15836242/22751251/bc4d6590-ee01-11e6-997b-6ddedb21ce93.png)


Then we closed the program and tried to reopen, but double clicking the SignStream icon yielded no result. Restarting the computer and trying several times to open the program by clicking the icon finally reopened the program. It took several attempts of double clicking SignStream for the window to open. 

Then we tested several options (i.e. from Rachel 57 into Rachel 45, from Rachel 43 into Rachel 57, and finally tried Rachel 43 into Rachel 45, which initially caused the problem). All of these worked properly. Last week, as well as earlier this morning, the program was switching between files just fine.

**Comment by gregorydimitriadis** [comment] 2017-02-08 18:34
Have either of these files had any other issues recently, like saving them?

**Comment by hammondcl** [comment] 2017-02-08 18:56
Not to our knowledge.

**Comment by gregorydimitriadis** [comment] 2017-02-08 18:57
And both have all of their videos attached when opened one-by-one?

**Comment by geograil** [comment] 2017-02-08 18:59
They do

**Comment by gregorydimitriadis** [comment] 2017-02-08 19:26
Thanks. Can you send me all those collection files via email? (thanks in advance)

**Comment by gregorydimitriadis** [comment] 2017-02-08 19:59
I can't seem to reproduce this one, moving around between all combinations of the files. Can it be reproduced on your end, or did it just occur this one time?

**Comment by geograil** [comment] 2017-02-08 20:09
It occurs randomly it seems

**Comment by hammondcl** [comment] 2017-02-27 16:47
This seems to be fixed

**Closed as completed** 2017-03-01 19:22 UTC
Labels: bug, complete
