### ISSUE TITLE
Data entry not working for signs on non-dominant hand

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#330] opened 2020-02-15 15:58 UTC
In 3.2.6, the attempt to enter data for signs entered on the non-dominant hand is not working.  Clicking on the Enter button does not work.  Nor does clicking on the Bypass sign bank button.

<img width="1088" alt="Screen Shot 2020-02-15 at 10 56 03 AM" src="https://user-images.githubusercontent.com/13629122/74591016-13b42e00-4fe2-11ea-8be1-c4ab243bbac9.png">

**Comment by gregorydimitriadis** [comment] 2020-02-18 18:47
@cneidle just realized something about this issue - is this valid to be annotating the gloss on the non-dominant hand, but not select any handshapes for it? I think this is why it is failing (in the code)

I would guess this came as a result from inserting from the sign bank (for "THREE") - which then placed the handshapes into the dominant slot. Is this as intended?

**Comment by cneidle** [comment] 2020-02-18 18:50
Hi Greg,

The problem is that when data is entered from the Sign Bank for a 1-handed
sign on the non-dominant hand, the handshapes should be copied into the
field for the non-dominant hand, not for the dominant hand!

I had chosen to “insert all data” for the sign THREE produced on the non-dominant
hand.  That is where the handshapes should have been inserted.

Hope that is clear.

Happy to discuss further…

Thanks,
 Carol

**Comment by gregorydimitriadis** [comment] 2020-02-18 18:52
@cneidle I see - so if we insert from sign bank into a morph-phon window which is annotating a 'non-dominant' gloss - then the dom in the SB should be swapped to non-dom in the morph-phon, and vice versa - correct?

**Comment by cneidle** [comment] 2020-02-18 18:57
exactly

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-09 04:01
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

1h signbank data inserted into non dom handshapes of 1h nondom 

Closing.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-09 04:01 UTC
Labels: bug, complete, priority HIGH, released
