### ISSUE TITLE
After clicking Display non-Empty fields, entire utterance moves with arrow keys - est. 3 hours

### ISSUE THREAD

**Issue by allihorowitz** [DCS-LCSR/SignStream3#198] opened 2017-11-29 23:07 UTC
If you want to see all fields that hold data and click the blue button in the side bar, all fields show as they should. (see first two screenshots)

![screen shot 2017-11-29 at 5 58 26 pm](https://user-images.githubusercontent.com/33096249/33403599-05ebc308-d52f-11e7-974c-32f4616b3466.png)

![screen shot 2017-11-29 at 5 58 39 pm](https://user-images.githubusercontent.com/33096249/33403608-0e798514-d52f-11e7-9dae-a46146a7ceb0.png)

Then when using the arrow keys to move through the utterance, the green bar and the entire utterance move together. The green bar appears to stay in place.

![screen shot 2017-11-29 at 6 00 24 pm](https://user-images.githubusercontent.com/33096249/33403681-51f3019e-d52f-11e7-8a8e-44921bd0d29b.png)

![screen shot 2017-11-29 at 6 00 43 pm](https://user-images.githubusercontent.com/33096249/33403683-5510c802-d52f-11e7-9407-4f154cdf9ea2.png)

This is fixed once the zoom is changed and potentially in other ways, though this is what I consistently have done to correct the bug. After changing the zoom, the green bar moves within the utterance normally.

![screen shot 2017-11-29 at 6 03 20 pm](https://user-images.githubusercontent.com/33096249/33403781-afe57b92-d52f-11e7-8987-52bae45a1bce.png)

![screen shot 2017-11-29 at 6 03 34 pm](https://user-images.githubusercontent.com/33096249/33403785-b42ff7ae-d52f-11e7-8d46-4339c8b1f48c.png)

![screen shot 2017-11-29 at 6 03 46 pm](https://user-images.githubusercontent.com/33096249/33403790-b70af4c4-d52f-11e7-98b3-efab6a4c45c6.png)

This happens consistently throughout different utterances in Jonathan 90 and is repeatable.

**Comment by cneidle** [comment] 2018-01-13 17:01
Medium priority.  Odd behavior.  Should not be happening.  Not as critical as other bugs but would be good to get this taken care of.

**Comment by gregorydimitriadis** [comment] 2019-05-03 17:25
Cannot reproduce this happening anymore. Possibly was fixed by earlier fixes.

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-07 06:20
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

fixed.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-07 06:20 UTC
Labels: bug, priority MED, cannot reproduce
