### ISSUE TITLE
Get Sign Bank command does not work

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#456] opened 2021-05-21 15:08 UTC
3.7.0_pre_2021_05_21_0908_cd9209c7

ios 10.12.6 

<img width="572" alt="Screen Shot 2021-05-21 at 11 03 05 AM" src="https://user-images.githubusercontent.com/13629122/119158845-a7b24800-ba24-11eb-95b7-c5db27a7a003.png">

**Comment by foltik** [comment] 2021-05-21 19:48
Can't reproduce. From what's shown, it's just the download that failed. It's possible the site hosting the signbank file was down at the time you ran the script. Does it consistently fail for you?

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-21 20:04
This occurs if when the access to the website fails for some reason.  Just retested in...

SignStream4_4.1.0_pre_2021_05_21_0909_15a705be
SignStream3_3.7.0_pre_2021_05_21_0908_cd9209c7

...and seemed to work.

Closing.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-21 20:04 UTC
Labels: SS-testing-May_21-version

**Comment by cneidle** [comment] 2021-05-21 20:09
OK - It is working now.  Thanks.
