### ISSUE TITLE
window disappears (v 3.4.0)

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#605] opened 2022-12-01 21:48 UTC
If you accidentally double-click on the title bar of the utterance window, the window disappears, and there's no way to get it back.

The only option is to quit, at which point there is an option to save.  But this is not right.  The available menus don't help:

<img width="843" alt="Screen Shot 2022-12-01 at 4 45 26 PM" src="https://user-images.githubusercontent.com/13629122/205165839-59578969-76ec-42c0-b8c8-172e563cf467.png">

**Comment by cneidle** [comment] 2022-12-20 18:13
This does not seem to be a problem in the December pre-release version.  Double-clicking on the title bar makes the window larger, rather than hiding it.  So that is good :-)

**Comment by cneidle** [comment] 2022-12-20 19:04
Correction:  This remains a problem in Mac OS 10.14.6.
The altered behavior of double-clicking on the title bar occurs only in Big Sur.
So, in Big Sur, the window does not get hidden, thereby averting this issue.
But in 10.14.6, the window still gets hidden, and we still have the problem described above.

**Comment by douglas-motto-at-rutgers** [comment] 2023-01-06 09:13
Utterance window maximizes and restores size on Mac OS 12 with 3.4.0 and latest 3.4.1_pre

**Comment by gregorydimitriadis** [comment] 2023-01-25 14:56
Cannot reproduce on macos13 with 3.4.1_pre_2022_12_16. It maximizes/restores the window size.

**Comment by cneidle** [comment] 2023-01-25 15:06
This is specific to OS versions where clicking on the title bar makes the utterance window disappear, rather than just resizing it.

I expect that this is not what happens in OS 13 (it does not happen in Big Sur).  

HOWEVER, the same problem exists in these newer OS's if you click on the middle button on the upper left of the utterance window,
<img width="67" alt="Screen Shot 2023-01-25 at 10 03 32 AM" src="https://user-images.githubusercontent.com/13629122/214598287-27f3a0be-ffc8-4ae5-bffd-47ab6d124797.png"> 
which has the same effect, and after doing this, the utterance window is then not recoverable.

**Comment by cneidle** [comment] 2023-02-18 18:39
Suggest adding a menu item:  Show all SignStream windows

**Comment by gregorydimitriadis** [comment] 2023-10-03 19:12
@cneidle shall we close this?

**Closed as completed** 2023-10-06 15:52 UTC
Labels: severity LOW
