### ISSUE TITLE
Field wrapper clickable heights off

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#276] opened 2019-07-23 15:26 UTC
This applies, at least, to the manual fields section of the utterance view. You can click slightly above a field and trigger the click action for that field (i.e. click above the horizontal line demarcating the field, and still trigger the click action). The heights of the wrappers are slightly off, and just need to be tweaked to be more exact.

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-07 18:41
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Assuming fixed...could not reproduce.

Closing.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-07 18:41 UTC
Labels: bug, complete, priority LOW, released
