### ISSUE TITLE
Disappearing Data (non-manuals) [w/ 218 est. 5 hours]

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#221] opened 2018-06-04 17:25 UTC
Hi Greg, 

I am working on non-manuals in file 82 of the Rachel and Jonathan dialog U29 of Rachel. I am having trouble with the eyebrow event. As I enter in the information, save it, and log out of SignStream the information is no longer there when I reopen SignStream. I have re entered the information three times today and it still hasn't saved. Please see screenshots below (the first is what information is entered and the second is where the information is missing)

![screen shot 2018-06-04 at 1 19 49 pm](https://user-images.githubusercontent.com/38887034/40931840-8a198ca6-67fa-11e8-86d3-b27d63123921.png) 

![screen shot 2018-06-04 at 1 19 09 pm](https://user-images.githubusercontent.com/38887034/40931851-93227132-67fa-11e8-9393-b505666241c2.png)

**Comment by gregorydimitriadis** [comment] 2018-06-05 19:17
@bugspotter33  @cneidle can you please provide the 82 collection? Thanks.

**Comment by gregorydimitriadis** [comment] 2018-08-17 15:39
I cannot reproduce this issue on this collection. I go to U29 and add an event for eye brows. Go back to database view, then back to utterance view. It still shows up. I save the collection, close signstream, reopen it and return to U29 - I still see the event. Same if I try for nearby utterances.

**Comment by cneidle** [comment] 2018-09-07 15:06
Suggest tabling this since it has not been reproduced, until such time as it recurs.

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-07 15:09
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

can not reproduce. Assumed fixed.

Closing.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-07 15:09 UTC
Labels: bug, priority HIGH, cannot reproduce
