### ISSUE TITLE
losing data

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#373] opened 2020-10-11 18:01 UTC
I lost about 15 minutes of work, because when I reopened the file, it was not my most recent saved version.  This has happened to me once or twice before.  The only thing I can think of that might have cause this is that I had done a search.  So in addition to saving my work every 30 seconds, which I have done religiously, when I changed the search domain, it asked if I wanted to save, and I clicked "yes".  I wonder if that restored some older "temp" file that the software might be using...  Just a thought.  I wonder how the saving works with the search...

**Comment by cneidle** [comment] 2020-10-11 18:39
I have a bad feeling wondering how much of my past work may have been lost without my noticing...

**Comment by gregorydimitriadis** [comment] 2020-10-12 21:07
Hi @cneidle - I see what you mean about the search, definitely could be a concern, and will look into it.

**Comment by cneidle** [comment] 2020-10-14 00:26
Why is it searching through a tmp file when searching through the currently opened collection?


<img width="314" alt="Screen Shot 2020-10-13 at 8 24 30 PM" src="https://user-images.githubusercontent.com/13629122/95929548-44777d80-0d92-11eb-97e0-c4821a333e94.png">

**Comment by gregorydimitriadis** [comment] 2020-10-15 18:47
@cneidle Can you send that collection file? thanks in advance

**Comment by cneidle** [comment] 2020-10-15 20:31
Attachments available until Nov 14, 2020
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAYWpcCaBcyV0oK3pY_NjOPdXR8NzAdZm9tV55bkpBZF3-iHufjEO8MRE%2F%24%7Bf%7D%3Fo%3DAgo7Zw1QZCxz5vsqW2VdzrAYUtJZv_u71SvhS0vXJ9MD%26v%3D1%26x%3D3%26a%3DCAogde9k52qL5P2p9WqssI8RErIP5adNYWT4jjlbBpDd0ZkScxD5p9bv0i4Y-bfRw9wuIgEAKggByAD_Z0f4hFIEV0fDc1oEDvDERGokN2PHgeicyuU25LLynQ2KCvAa6KVeTcCH7KLNDEytblJd1vu6ciTjsq36uv8Ng-yB-M4GE7SBMZvPbRn1EO-vLnKa4ALNdREQSd0%26e%3D1605385870%26fl%3D%26r%3DB5A65625-0636-4AA5-9CF4-C459C10C92A0-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D309D2BFD-1216-4681-A069-8CF12C65BF5F%26p%3D61%26s%3D50JmkJGBn8AZwlEaKWLjZuD3m4E&uk=tOaoexp4ybVFgIHNIZ1QgQ&f=5-Ben-Deaf-Grunts.ss3&sz=395205>5-Ben-Deaf-Grunts.ss3
395 KB


Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAQTNuhMyv3ptkyogFC4kalRUHGJdASqjA7_PbMHujvPEIDTTXWN3328j%2F%24%7Bf%7D%3Fo%3DAvRAregsSr5SMR-AGNYQe5Q7fVxwPxLXD5c2gEZt196F%26v%3D1%26x%3D3%26a%3DCAogpWOm7JU2kieM4fSqpSOEh2RlOBxssGcb4QX-m4HuzqcScxDLqdbv0i4Yy7nRw9wuIgEAKggByAD_JEUKIlIEVBxiXVoEd99vI2okaS7b17cEbW9X6isbyQcSM7khrlYq-o-XxC_po4KKDUE0a6M0ciTXOVkds8QwKbTKGSy2jmM7xdpGpXfy_8OH_89bR7zSZr6uN3Y%26e%3D1605385870%26fl%3D%26r%3D1D0B9D1F-D770-4BF8-B839-CC06C898ABAF-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D309D2BFD-1216-4681-A069-8CF12C65BF5F%26p%3D61%26s%3DqwYEqieV3D2vuDfL0bgI5taUNS4&uk=E5rVuU6811FmVK6TVE8_bg&f=5-Deaf-Grunts.mov&sz=51448206>5-Deaf-Grunts.mov
51.4 MB

**Comment by gregorydimitriadis** [comment] 2020-10-22 20:02
@cneidle having difficulty reproducing this - are there a series of steps which you can currently do which can cause this to occur again?

**Comment by cneidle** [comment] 2020-10-22 20:05
One thing I noticed about the search domain showing up as a tmp file is that this happened more than once (but not always) when, e.g., I did a search, it produced multiple results, I went to view the first result, made a change, saved the file, went back to the search window results, looked at the second result, etc.   In other words, continuing with the results in the search window after I had done a file save.

**Comment by gregorydimitriadis** [comment] 2020-11-05 16:19
@cneidle question while still looking into this: do you recall if this occurred for "full" glosses? By full I mean - typed the word on the gloss line, set the start/end times, and selected handshapes. Or was it "less than full" - i.e. just typed the word and/or set the start/end times.

**Comment by cneidle** [comment] 2020-11-05 16:21
NOt sure what you are asking about here.  These were searches.  Everything was annotated.  Does this question refer to a different bug report ??

**Comment by gregorydimitriadis** [comment] 2020-11-05 16:30
Referring to this:
> I went to view the first result, made a change, saved the file, went back to the search window results, looked at the second result, etc

Were the changes (which went subsequently missing) to only existing glosses, or for new glosses as well?

**Comment by cneidle** [comment] 2020-11-05 16:31
I don’t believe I created any new glosses…

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-29 06:01
per emails...

Re [1] , the problem no longer seems to be occurring.  thanks.

closing

**Closed as completed by douglas-motto-at-rutgers** 2021-05-29 06:01 UTC
