### ISSUE TITLE
error in the warning messages - est. 4 hours

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#224] opened 2018-06-06 18:29 UTC
I am working in the Cory 113 file U54 and I have been getting a warning message when entering data in the morph-info window when I am certain the sign has been saved/exists in the sign bank. I searched the sign SCHOOL and found it in the sign bank. However when I press enter on the morph-info window the warning message appears and tells me the sign is not in the sign bank. 

![screen shot 2018-06-06 at 2 25 45 pm](https://user-images.githubusercontent.com/38887034/41057750-f19519a8-6995-11e8-990d-be165b1d17a7.png)

![screen shot 2018-06-06 at 2 25 23 pm](https://user-images.githubusercontent.com/38887034/41057753-f41db70c-6995-11e8-8cf0-73b74e9d1665.png)

**Comment by gregorydimitriadis** [comment] 2018-06-06 18:56
@bugspotter33 from the "Sign Bank" window - did you first click "Insert All Data"? That should've transfered over to the "Morph Phon" window all the information from that sign (e.g. the primary entry value, etc)

**Comment by cneidle** [comment] 2018-06-06 18:57
Hi Greg,

It should not be necessary to re-enter information for glosses that are already
coded and that already exist in the sign bank.  

Thanks,
 Carol

**Comment by gregorydimitriadis** [comment] 2018-06-06 19:00
@cneidle True, but I think the logic for "enter"ing out of that window looks at whether there is values for "primary entry" and "entry/variant", and if they are in the sign bank. If they're blank it will give this error message.

**Comment by cneidle** [comment] 2018-06-06 19:01
Hi Greg,

We’ve been through this before.

The entry/variant uniquely determines what sign it is.

It should not be necessary to have the primary entry slot filled in order to avoid
an error message.

I thought this got fixed long ago…

Thanks,
 Carol

**Comment by gregorydimitriadis** [comment] 2018-06-06 19:43
Carol,


Ah, sorry - you're right. I had forgotten about that and was still thinking about the old way.


So this appears to be something different happening.


-Greg

________________________________

**Comment by cneidle** [comment] 2018-08-04 19:59
increased priority by a little

**Comment by gregorydimitriadis** [comment] 2018-11-30 23:00
@cneidle is there an up-to-date version of this collection?

I have a possibly old verison of Cory 113 which shows something slightly different for the SCHOOL gloss there.

**Comment by cneidle** [comment] 2018-12-02 19:26
Most recent:



thanks,
 Carol

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-07 15:24
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
works for SCHOOL.

Assuming root cause was fixed.

Closing.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-07 15:24 UTC
Labels: bug, complete, priority MED, released
