### ISSUE TITLE
Reopening file created with April 1 test version - errors reported

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#494] opened 2022-04-02 11:21 UTC
I created a new file with the April 1 test version.   

<img width="737" alt="Screen Shot 2022-04-02 at 7 19 57 AM" src="https://user-images.githubusercontent.com/13629122/161380816-ca9e08a6-90c2-4907-b00d-ad3529b7677a.png">

 I saved it and closed SignStream.  I relaunched SignStream and attempted to re-open that file, but... 

<img width="742" alt="Screen Shot 2022-04-02 at 7 14 38 AM" src="https://user-images.githubusercontent.com/13629122/161380690-3b3b1d5e-93c8-47aa-9a10-e172aee6219d.png">

Note that the error text does not wrap so here is what I saw when I opened that, in two parts:

<img width="1624" alt="Screen Shot 2022-04-02 at 7 17 57 AM" src="https://user-images.githubusercontent.com/13629122/161380759-996746cb-3444-4fed-a533-557e1bc60c79.png">

<img width="1184" alt="Screen Shot 2022-04-02 at 7 18 06 AM" src="https://user-images.githubusercontent.com/13629122/161380764-98944967-1fb4-4af4-854a-90dfd1e12e06.png">

**Comment by cneidle** [comment] 2022-04-02 11:24
<img width="814" alt="Screen Shot 2022-04-02 at 7 24 02 AM" src="https://user-images.githubusercontent.com/13629122/161380933-cd8529c2-42bf-40cd-bae5-16ef9da94a7b.png">

**Comment by gregorydimitriadis** [comment] 2022-04-04 13:36
@cneidle can you please send the file for this one? Thanks in advance

**Comment by cneidle** [comment] 2022-04-04 14:00
I was able to reproduce this in another newly created file.  The errors occurred after I added a gloss to the RightHandParticipant.

<img width="1445" alt="Screen Shot 2022-04-04 at 9 56 19 AM" src="https://user-images.githubusercontent.com/13629122/161560017-71beb88a-fa76-4ba1-be60-b3c9ce12e677.png">

<img width="1556" alt="Screen Shot 2022-04-04 at 9 58 41 AM" src="https://user-images.githubusercontent.com/13629122/161560238-4134ab33-a51b-4b0b-80c6-d163717bfdb9.png">

<img width="1373" alt="Screen Shot 2022-04-04 at 9 58 48 AM" src="https://user-images.githubusercontent.com/13629122/161560256-e2c2e6a5-c913-451a-8f0a-ab315a51c5fc.png">


[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/8410300/SignStreamOut.txt)

**Comment by douglas-motto-at-rutgers** [comment] 2022-04-05 04:20
word wrapped in SignStream3-3.4.0_pre_2022_04_04_1647_dd5956a3

**Comment by gregorydimitriadis** [comment] 2022-04-05 14:44
@cneidle I did these steps could not reproduce:
* create a new collection
* add video, DefaultAnnotator, RightHandParticipant/Jonathan/Rachel as participants
* confirm
* create a new segment tier associated with RightHandParticipant
* create a new temporal partition and the segment tier associated with Rachel
* create an utterance for the first temporal partition (above RightHandParticipant)
* enter that utterance, create a gloss (just the gloss, nothing else, as in your collection)
* save the collection
* reopen the collection - not seeing the errors you are seeing.

Is there any step above which I missed which resulted in your seeing those errors? I see why they are occurring based on the collection file's xml, but not sure how that arised.

**Comment by cneidle** [comment] 2022-04-05 15:03
This is happening often for me.  It seems to be triggered by entering a gloss in an utterance within the RightHandParticipant tier.  


Also, reopening files that previously had errors seems to multiply them... Here's the latest...  I will email this file.

<img width="834" alt="Screen Shot 2022-04-05 at 10 58 39 AM" src="https://user-images.githubusercontent.com/13629122/161783972-3654aa68-89f9-49ba-9f61-a0cd062691c1.png">

<img width="1643" alt="Screen Shot 2022-04-05 at 10 59 03 AM" src="https://user-images.githubusercontent.com/13629122/161783997-fe8984a7-aee9-4670-b06e-48085cfbd251.png">

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/8419344/SignStreamOut.txt)

**Comment by cneidle** [comment] 2022-04-05 15:23
I created a new file.  Saved it.  Saved a copy.  Further edited the copy by adding a few glosses - in both the Rachel tier and the RightHand tier.  Got this.

Will email you both the before and after files...

<img width="1125" alt="Screen Shot 2022-04-05 at 11 19 28 AM" src="https://user-images.githubusercontent.com/13629122/161788545-47e66aa1-fe84-42ce-88ee-b9c7e9884c10.png">

<img width="1637" alt="Screen Shot 2022-04-05 at 11 19 56 AM" src="https://user-images.githubusercontent.com/13629122/161788577-b1096dac-edf3-4e6e-8a48-8ce237e81229.png">

<img width="1256" alt="Screen Shot 2022-04-05 at 11 20 02 AM" src="https://user-images.githubusercontent.com/13629122/161788620-c1b9b7d7-986f-4560-ba86-1c6dd8c98bd1.png">

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/8419544/SignStreamOut.txt)

**Comment by gregorydimitriadis** [comment] 2022-04-05 19:45
I can reproduce it.

**Comment by gregorydimitriadis** [comment] 2022-04-08 14:14
Fixed in upcoming release version 3.4.0_pre_2022_04_08_1303_81ad7079 - might require additional testing.

**Closed as completed by gregorydimitriadis** 2022-04-08 14:14 UTC
Labels: APRIL-1-2022
