### ISSUE TITLE
changing type of sign in Sign-Phon window can wipe out hand information

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#268] opened 2019-06-24 23:25 UTC
If a sign has already been annotated, and then you decide, e.g., to change its classification from classifier to lexical sign, what happens is pretty annoying:

Because the default number of hands for lexical signs is 2, then even though this had already been categorized as a 1-handed sign, with a specific handshape, the number of hands
changes to 2 and the selected handshapes are wiped out.

It would be great if the default number of hands could be exactly that:  a default if handshapes have not already been specified.

Priority:  low  - but FYI.   THANKS.

And a question:  Since this upper portion of the sign-phon window can be
modified from the future location tab, what happens to handshapes if 
you make a change in the location window from classifier to lexical sign --
unless this gets fixed. 
Perhaps a reason *not* to have this selection available from the location tab...
unless this does get fixed. (Changing from classifier to lexical, e.g., should
*not* change selections about number of hands or handshapes, but if it does,
this is a real problem for editing in the location tab.)

**Comment by gregorydimitriadis** [comment] 2019-06-25 13:27
Hi @cneidle -- trying to understand this one.

For the first part -- I cannot reproduce this with a few random glosses I've chosen. I change them to be a Classifier, then select one-handed for them. I see the top row of handshapes filled in, only. Then I select Lexical. It automatically switches to two-handed, and copies the top row of handshapes to the bottom row. I have yet to see the handshapes disappear from both rows. Is there any set of steps you can do to reliably reproduce this? Is it on all glosses you try it for?

For the second part, your question -- the location tab will appear as the handshape tab currently does. It is under the sign type selection radio buttons. Switching the sign type affects certain things in the handshape tab. I don't know whether it would change anything in the location tab. Also I don't believe changing anything in the location tab will affect anything about the sign type. Please correct my thinking if this is incorrect.

**Comment by cneidle** [comment] 2019-06-25 13:54
Hi Greg,

The problem occurs when going from a 1-handed classifier sign (the cases I was facing
involved a 1-handed classifier sign on the non-dominant hand) to a lexical sign.

What consistently happens is the the number of hands changed from 1 to 2
(the default for lexical signs) and the handshape information is wiped out.

This happened for me yesterday 100% of the time (and there were many, many 
cases, in lots of files, as I was making a systematic correction).

It is a PROBLEM if changing something in one tab (e.g., changing the sign type
while in the location tab) causes changes to occur in another tab that is not visible.

The ideal behavior, in any case, would be that if you change the sign type after handshapes
have been entered (and therefore after number of hands and handshapes have been 
determined by the user), NOTHING should happen to alter the number of hands
or the handshapes.

If the user has coded all the properties of the sign, but realizes its sign type was not
correctly identified, the user should not have to reset anything else but the sign type.

THANKS,
 Carol

**Comment by gregorydimitriadis** [comment] 2019-06-25 14:09
@cneidle Thanks, I see - I can reproduce it by making the one-handed sign on the non-dominant hand. To fix that would be a simple issue.

On this, though:

> The ideal behavior, in any case, would be that if you change the sign type after handshapes
have been entered (and therefore after number of hands and handshapes have been
determined by the user), NOTHING should happen to alter the number of hands
or the handshapes.

This may be a big change, based on how that panel is coded. Many of the sign type buttons will automatically change stuff regarding number of hands, etc, and have other triggers as well.

**Comment by cneidle** [comment] 2019-06-25 14:27
Thanks, Greg.

Well, that is unfortunate.  It is not possible to bypass those triggers if handshapes
have been entered ??

If that is the case, then I really think it is important that the user only be allowed to change
sign type information in the handshape tab.

What about having the tabs above the sign type information:

Handshapes/sign type  |  Location   |  etc.

That would also give more display space for location…

Thanks!

Best,
 Carol

**Comment by gregorydimitriadis** [comment] 2019-06-25 15:04
@cneidle It may be doable to bypass the triggers if there are handshapes. Will investigate this.

I'm more skeptical of merging the sign type and handshape information.

**Comment by cneidle** [comment] 2020-11-01 16:52
This is still a problem, and EXTREMELY annoying.  If you have already entered handshapes (whether on 1 or 2 hands), and you change the sign type, this should NOT automatically change the number of hands for the sign, nor should it enter additional handshapes or wipe out handshapes that have already been entered...

**Comment by cneidle** [comment] 2020-11-01 18:39
Just to be explicit about what happens but should not happen:  

1) If I change the sign below from Number to Lexical, it makes it 2-handed, same handshapes, and adds handshapes to the non-dominant hand.  (If this had been a 2-handed sign with different handshapes on the 2 hands, it would have over-written that to make the handshapes on the 2 hands the same, because the default for lexical signs is 2-handed, same handshapes on both hands).

<img width="597" alt="Screen Shot 2020-11-01 at 1 18 31 PM" src="https://user-images.githubusercontent.com/13629122/97811224-fc3bd480-1c46-11eb-8901-78a62e126659.png">

<img width="602" alt="Screen Shot 2020-11-01 at 1 18 40 PM" src="https://user-images.githubusercontent.com/13629122/97811225-fe9e2e80-1c46-11eb-9e14-74154f79179e.png">

Likewise, if I change the sign below from a 1-handed lexical sign to a classifier, it does the same thing: it makes it 2-handed same handshapes (the default apparently for classifiers).  Just two examples, but changing the type of sign overwrites all information about number of hands and handshapes on each with the default values for the new sign type.  This absolutely should not happen.  And if a user is unaware, and thinks that all that he/she changed was the sign type and proceeds to save, incorrect information will be entered without the user even noticing...  Would be important to fix this.  THANKS.

<img width="590" alt="Screen Shot 2020-11-01 at 12 49 34 PM" src="https://user-images.githubusercontent.com/13629122/97811246-3e651600-1c47-11eb-842d-cb27e7a6707c.png">

<img width="595" alt="Screen Shot 2020-11-01 at 12 49 42 PM" src="https://user-images.githubusercontent.com/13629122/97811244-3e651600-1c47-11eb-8a46-00bccfb53fa8.png">

**Comment by gregorydimitriadis** [comment] 2020-11-02 13:49
@cneidle I think when we did this before we opted for the 'quick fix' to address the immediate issue (hands going from 1 to 2 and handshapes being deleted), and didn't account for the broader (no changes to handshapes or number of hands) issue - this will still take a lot of time to refactor the way the original code worked to accomplish properly - just FYI, but we can look into it.

**Comment by cneidle** [comment] 2020-11-02 14:38
Hi Greg,

I would have, perhaps naively, thought that this would not be difficult.

When there is a change to the type of sign, the program needs to see whether
handshapes have already been selected.  If yes, then change nothing other
than the category of the sign.  If no, then also implement the category default
settings.

Is that really very difficult to implement?

Thanks very much,
 Carol

**Comment by cneidle** [comment] 2020-11-03 16:57
FWIW - I would say this priority is higher than "low" (modiying what I suggested above)...   This is a potential source of data loss.

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-07 17:59
Part of larger discussion.

Keeping open.

**Comment by cneidle** [comment] 2021-10-15 22:42
is this fixed?

**Comment by gregorydimitriadis** [comment] 2021-10-21 14:46
This is fixed in the pending upcoming version.

**Closed as completed** 2022-09-20 14:36 UTC
Labels: bug, enhancement, complete, priority MED, PRI 1
