### ISSUE TITLE
Moving video with arrow keys - est. 5 hours

### ISSUE THREAD

**Issue by rklopez** [DCS-LCSR/SignStream3#17] opened 2015-08-05 19:14 UTC
When in SignStream3, after opening the nonmanual fields and adding new values, you need to click on the video to use the arrow keys to move it. If you are clicked on the SS3 screen, the video will not move with the arrow keys.

**Comment by kwasiopoku** [comment] 2015-08-26 19:09
Carol indicated on our spent planning that this is not a high priority and should consider moving to a different sprint.

**Comment by blazetravis** [comment] 2015-11-03 20:45
In working with non-manuals more lately, and in helping Chris learn how to use SignStream as well, I would like to suggest that this bug be moved to an upcoming sprint. It is very frustrating to have to keep clicking between windows. We have found that having to do so is a much less efficient and effective way of using SignStream. Thanks!

**Comment by gregorydimitriadis** [comment] 2015-11-04 20:29
@blazetravis - Duly noted. As the current sprint is already planned, it might be tight to include this ticket as well, but I will spend some time later this week trying to get an estimate of how long it may take to complete this. If it seems doable, I'll move it into this current sprint - and if not then it will definitely be prioritized for the next one.

**Comment by gregorydimitriadis** [comment] 2015-11-09 16:27
@blazetravis - Can I ask you to please test if the ability to hit the arrow keys to move the video returns in the main SignStream window if you: hide and then show the bottommost segment (or the only if there's only one segment).
Thanks, Greg

**Comment by blazetravis** [comment] 2015-11-09 18:31
It does indeed return the ability to use the arrow keys if I hide and then show the pane. How strange.

**Comment by gregorydimitriadis** [comment] 2015-11-09 19:15
Thanks for that. Since there is this workaround, I will put this issue on the radar for the next sprint.

**Comment by hammondcl** [comment] 2016-04-19 14:24
Update: This bug was able to be worked around with the hide pane/ show pane fix and with the last sprint, seemed to stop happening because you can now use the + and - buttons to add and remove fields. Recently, we have discovered that if you click and drag nonmanual fields to rearrange them, this bug returns. If you click on the video window, the green line will once more move with the arrow keys, but stops working again if you click back on the yellow SignStream window. At this time, we do not have any workarounds.

**Comment by gregorydimitriadis** [comment] 2016-09-29 14:04
@hammondcl Hi Chelsea, can you please verify whether this bug is still occurring in the latest version? Thanks!

**Comment by hammondcl** [comment] 2017-02-22 16:17
Hi Greg, this was mostly not an issue other than very occasionally, but has occurred quite a lot recently. It seems to be most prevalent in the Cory files. I'm not sure how or if that is related, but I've noticed it only a few times during each of my shifts here. I've been focusing mainly on Rachel files, but I'm working in Cory today and every time I click on the yellow SignStream window, I have to reselect the video window in order to be able to frame through. With nonmanuals, I go through almost every most of the video frame by frame, so while this is not a huge issue, it is rather annoying.

**Comment by gregorydimitriadis** [comment] 2017-02-22 17:02
Will put this back on the queue for inspection.

**Comment by hammondcl** [comment] 2017-02-27 17:41
This issue occurred on Friday, but the workaround of selecting the video window did not re-enable the arrow keys. The issue occurred primarily when using the "Next/ Previous Utterance" buttons and was noticed in Rachel 51. We cannot reproduce it today, but on Friday, the arrow keys were not useable.

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-06 17:46
Keys work as of

SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

**Closed as completed by douglas-motto-at-rutgers** 2021-05-06 17:46 UTC
Labels: bug
