### ISSUE TITLE
One-frame glosses dropping handshapes - est. 20 hours

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#104] opened 2016-09-28 17:27 UTC
This bug seems to happen unreliably and unpredictably, but occasionally, if a main gloss is only one frame long, the handshape information will get dropped. This thread will serve as a location for us to compile examples as they occur.

**Comment by hammondcl** [comment] 2016-09-28 17:42
Rachel 43, U9 IX-1p

![screen shot 2016-09-28 at 1 32 03 pm](https://cloud.githubusercontent.com/assets/15836242/18924971/16ccfc78-8580-11e6-84ab-2185483519a3.png)

---

Rachel 43, U11 POSS-1p

![screen shot 2016-09-28 at 1 28 04 pm](https://cloud.githubusercontent.com/assets/15836242/18924777/7590d49c-857f-11e6-9e4a-8c800fd7a468.png)

---

Rachel 43, U16 IX-3p:i

![screen shot 2016-09-28 at 1 29 01 pm](https://cloud.githubusercontent.com/assets/15836242/18924847/a8f5f114-857f-11e6-97f7-faf5320b51e0.png)

---

Rachel 43, U23 IX-1p

![screen shot 2016-09-28 at 1 36 32 pm](https://cloud.githubusercontent.com/assets/15836242/18925133/ae820c0c-8580-11e6-9455-750775f5e3ed.png)

**Comment by gregorydimitriadis** [comment] 2016-09-28 17:52
Verified this occurring on my end, as well - marking as bug.

The odd thing is that only 2/4 of the above examples were displaying as incorrect on the collection on my machine. Still not sure what the pattern is/what differentiates them, etc.

**Comment by hammondcl** [comment] 2016-10-05 17:24
Rachel 45, U8 IX-3p:i

![screen shot 2016-10-05 at 1 12 51 pm](https://cloud.githubusercontent.com/assets/15836242/19123864/90258bfc-8afe-11e6-8a09-0f00438d8d42.png)

---

Rachel 45, U9- Five drops: IX-3p:j, IX-loc:i

![screen shot 2016-10-05 at 1 13 48 pm](https://cloud.githubusercontent.com/assets/15836242/19123905/becde30a-8afe-11e6-8a3b-14f2977995bd.png)

IX-1p, IX-3p:i, IX-1p

![screen shot 2016-10-05 at 1 14 21 pm](https://cloud.githubusercontent.com/assets/15836242/19123924/db5c98d6-8afe-11e6-841d-0425c6ba668f.png)

---

Rachel 45, U14 IX-3p:j

![screen shot 2016-10-05 at 1 15 30 pm](https://cloud.githubusercontent.com/assets/15836242/19123958/089a6a3a-8aff-11e6-9728-58dfc4c37634.png)

**Comment by hammondcl** [comment] 2016-10-05 17:25
Rachel 44, Rachel 50, and Rachel 51: No dropped single-frame gloss handshapes

**Comment by geograil** [comment] 2016-10-07 21:04
10/7 Additions: 

Rachel 51, U25 IX-3p:j    (--we double check each file/utterance before marking the number of drops and reporting them. On 10/5, all of Rachel 51 was intact; therefore, this was dropped within the past few days.)
![screen shot 2016-10-07 at 11 18 52 am](https://cloud.githubusercontent.com/assets/19953651/19196118/3ee76906-8c82-11e6-979e-0a1c21a74621.png)

**Comment by geograil** [comment] 2016-10-07 22:24
10/7 Situation Update (apologies for length - there have been significant developments):

I came in and continued checking the files for dropped handshapes in one-frame glosses (subsequently abbreviated "1F drops" and "drops"). We left a reminder for me to recheck a gloss in Rachel 51, U21, so that's where I started. While the handshape for the gloss in question was intact, I did find a 1F drop in U25 (reported above). We last checked that same file in its entirety on Wednesday, 10/5. We double checked all utterances and found all of Rachel 51 to be intact at that time. Upon seeing the 1F drop in U25 today, I have to conclude that the handshape was dropped within the past two days. 

This is concerning because the issue is potentially persistent in the current version of SignStream and not a leftover result of prior SS3 bugs/issues. I decided to recheck the files we had already checked in case other 1F drops happened in the past two days; luckily, no additional drops were found in those.  

Because the issue seems to be random in both timing and cause, I made a spreadsheet to keep track of exactly which file/utterances have 1F glosses in general, which ones are showing the 1F drops, and a log indicating that they have been reported here. If the 1F drops are going to randomly occur at this point, I wanted to have a reference point to facilitate tracking, reporting, and eventually reinserting the dropped handshapes. In my time today, I was able to go through the five files we checked so far and populate the corresponding 1F drop data:
- Rachel 43
  - Total 1F glosses: 29
  - Total 1F drops: 4
    - U9; overall 1F glosses - 4; 1F drops - 1 
    - U11; overall 1F glosses - 2; 1F drops - 1
    - U16; overall 1F glosses - 2; 1F drops - 1
    - U23; overall 1F glosses - 2; 1F drops - 1
- Rachel 44
  - Total 1F glosses: 10
  - Total 1F drops: 0
- Rachel 45
  - Total 1F glosses: 34
  - Total 1F drops: 7
    - U8; overall 1F glosses - 4; 1F drops - 1 
    - U9; overall 1F glosses - 7; 1F drops - 5
    - U14; overall 1F glosses - 3; 1F drops - 1
- Rachel 50
  - Total 1F glosses: 6
  - Total 1F drops: 0
- Rachel 51
  - Total 1F glosses: 35
  - Total 1F drops: 1
    - U21; overall 1F glosses - 1; 1F drops - 1 

While only based on 5 files so far, there seems to be a pattern emerging - 
1. The files with a substantial number of 1F glosses in total appear to be the only files showing the 1F drops. Rachel 43, 45, and 51 all had 29 or more 1F glosses across the file. Rachel 44 and 50 had 10 or fewer.
2. The drops are most often occurring in utterances with more than one 1F gloss. Out of the 12 drops seen from these files, 10 of them were in utterances that individually had 2 or more 1F glosses; only 2 occurred in utterances with only one 1F gloss, which then dropped its handshape.

I'm not sure if this helps for troubleshooting the bug, but it was a strong correlation despite the low number of sample files so far. I am going to proceed through the rest of the Rachel files and then move to Cory and Jonathan over the next few weeks. Is there a place we can put a running file summary that Chelsea and I are both able to update in terms of the parameters listed above? I think it would be more organized and effective to look at in comparison to posting segmented blocks in different comments, but I'm not sure if we use anything other than the github comment structure.

-Graham

**Comment by gregorydimitriadis** [comment] 2016-10-10 13:52
Graham - I think for now listing the various occurrences of the issue here in this github ticket should suffice. Thanks!

**Comment by geograil** [comment] 2016-10-12 16:59
**10/12/16**

Rachel 52, U11 IX-3p:i
![screen shot 2016-10-12 at 12 08 30 pm](https://cloud.githubusercontent.com/assets/19953651/19318138/67018a92-9075-11e6-93ae-9dac64067154.png)

---

Rachel 52, U13 IX-3p:i and IX-3p:i
![screen shot 2016-10-12 at 12 09 37 pm](https://cloud.githubusercontent.com/assets/19953651/19318185/a784780e-9075-11e6-938f-7b498bc4e51f.png)

---

Rachel 52, U19 IX-2p and IX-2p
![screen shot 2016-10-12 at 12 10 29 pm](https://cloud.githubusercontent.com/assets/19953651/19318218/d5202ed4-9075-11e6-8b23-a1efe7063c9a.png)

---

Rachel 52, U20 POSS-3p:i and IX-1p
![screen shot 2016-10-12 at 12 11 05 pm](https://cloud.githubusercontent.com/assets/19953651/19318258/021ee20e-9076-11e6-9e46-379f548bc1a0.png)

**Comment by geograil** [comment] 2016-10-12 17:24
**10/12/16**   

NOTE: 16 out of 32 1-frame glosses in this file dropped handshape information. Rachel 53, which has 37 1-frame glosses, had no drops. 

Rachel 55, U1 IX-loc:i
![screen shot 2016-10-12 at 1 00 09 pm](https://cloud.githubusercontent.com/assets/19953651/19319665/e44d88ce-907b-11e6-9c0b-9927d3643b3a.png)

---

Rachel 55, U3 IX-3p:i
![screen shot 2016-10-12 at 1 02 13 pm](https://cloud.githubusercontent.com/assets/19953651/19319718/26b2fa3c-907c-11e6-988d-aaf7eaeccade.png)

---

Rachel 55, U6 IX-1p and IX-1p
![screen shot 2016-10-12 at 1 04 02 pm](https://cloud.githubusercontent.com/assets/19953651/19319770/5fbdff2a-907c-11e6-8fa3-5c65af0f1604.png)

---

Rachel 55, U7 IX-3p:i and IX-3p:i
![screen shot 2016-10-12 at 1 05 13 pm](https://cloud.githubusercontent.com/assets/19953651/19319801/8fa40fe0-907c-11e6-9bc9-5abffc2d1d64.png)

---

Rachel 55, U9 IX-3p:i
![screen shot 2016-10-12 at 1 06 56 pm](https://cloud.githubusercontent.com/assets/19953651/19319840/c84f8a54-907c-11e6-82ed-6ae4530c65d3.png)

---

Rachel 55, U11 IX-loc:i and IX-3p:i
![screen shot 2016-10-12 at 1 08 03 pm](https://cloud.githubusercontent.com/assets/19953651/19319884/f5365106-907c-11e6-8c6f-5d74416c266b.png)

---

Rachel 55, U17 IX-3p:1
![screen shot 2016-10-12 at 1 10 59 pm](https://cloud.githubusercontent.com/assets/19953651/19320063/be45f52e-907d-11e6-898b-d683800c5541.png)

---

Rachel 55, U18 IX-1p
![screen shot 2016-10-12 at 1 16 04 pm](https://cloud.githubusercontent.com/assets/19953651/19320170/3397fa5c-907e-11e6-9b57-b904c01ac10a.png)

IX-1p, IX-3p:i
![screen shot 2016-10-12 at 1 16 30 pm](https://cloud.githubusercontent.com/assets/19953651/19320187/3fcdb366-907e-11e6-9947-f9daa154cabf.png)

---

Rachel 55, U21 POSS-1p
![screen shot 2016-10-12 at 1 19 06 pm](https://cloud.githubusercontent.com/assets/19953651/19320271/86763752-907e-11e6-8b4f-b1263b1aed25.png)

---

Rachel 55, U25 IX-2p
![screen shot 2016-10-12 at 1 20 51 pm](https://cloud.githubusercontent.com/assets/19953651/19320326/c018597c-907e-11e6-892a-c8b6a00ba55a.png)

---

Rachel 55, U26 IX-3p:i
![screen shot 2016-10-12 at 1 21 46 pm](https://cloud.githubusercontent.com/assets/19953651/19320342/e24441aa-907e-11e6-8354-c012c0e1bca8.png)

**Comment by geograil** [comment] 2016-10-12 18:11
10/12/16

Rachel 57, U4 IX-1p
![screen shot 2016-10-12 at 2 05 10 pm](https://cloud.githubusercontent.com/assets/19953651/19321913/ebe74b02-9084-11e6-976d-8292bf95f063.png)

---

Rachel 57, U9 IX-3p:i and IX-3p:i
![screen shot 2016-10-12 at 2 05 44 pm](https://cloud.githubusercontent.com/assets/19953651/19321933/0326e110-9085-11e6-8ecd-93b9ffb5a3fa.png)

---

Rachel 57, U17 IX-1p and IX-1p
![screen shot 2016-10-12 at 2 07 28 pm](https://cloud.githubusercontent.com/assets/19953651/19322002/40aaf77e-9085-11e6-8134-4a935e2305e7.png)

---

Rachel 57, U19 IX-1p
![screen shot 2016-10-12 at 2 08 45 pm](https://cloud.githubusercontent.com/assets/19953651/19322027/6a066950-9085-11e6-8e7f-7b377cac3aec.png)

---

Rachel 57, U21 IX-1p
![screen shot 2016-10-12 at 2 09 27 pm](https://cloud.githubusercontent.com/assets/19953651/19322049/85877246-9085-11e6-825e-6af40a1a2afc.png)

---

Rachel 57, U22 IX-1p
![screen shot 2016-10-12 at 2 10 35 pm](https://cloud.githubusercontent.com/assets/19953651/19322079/ab4b19d8-9085-11e6-83f3-c9f21eb00fe8.png)

**Comment by geograil** [comment] 2016-10-14 19:40
10/14/16

Rachel 62, U14 IX-loc:i
![rachel62u14](https://cloud.githubusercontent.com/assets/19953651/19400509/89a1ae6e-9224-11e6-8232-761900fff51e.png)

---

Rachel 56, 58, 59, 61, and 65 all had no 1F drops

To be checked: Rachel 63 and 66, Cory 107 (if working) - 115, Jonathan 90-95 and 97-98.

Rachel 60 + 64, Cory 100-106, and Jonathan 96 are marked as files we should not work with; please let me know if that changes or if they should be checked.

**Comment by geograil** [comment] 2016-10-20 13:59
10/19/16

Rachel 63 and Rachel 66 have no IF drops. 
All Rachel files have been checked at this point except for 60 and 64 since they are marked as ones we shouldn't open/work with. 

I'll be moving on to Cory or Jonathan files on Friday 10/21

**Comment by hammondcl** [comment] 2016-11-02 16:29
Last week (10/26), Graham and I were looking at nonmanuals in Rachel 43 when we noticed that many additional 1-frame glosses throughout the entire file had dropped handshapes. Originally the file had 4 1-f drops and upon checking it again, had 14 drops. We checked again today and SignStream had repopulated the new ten drops (seemingly with the correct handshapes), but the original four remain dropped. 

It does not appear that this happened in any other file or with any distinct cause, but we wanted to report this phenomenon.

**Comment by geograil** [comment] 2017-01-25 18:16
Am I all set to start adding the dropped handshapes back into the files?

**Comment by gregorydimitriadis** [comment] 2017-01-25 18:21
@geograil Yes, once you've got the latest version (released today) you're good to go.

**Comment by gregorydimitriadis** [comment] 2017-01-31 21:26
Note on bugs #104, #105, #108:

There were some issues in the data saved in the annotation files themselves, so to the best of my ability I have corrected any dropped or missing information, but some of it is lost. For example, for most of the handshape drops, the data is missing and can't be retrieved based solely on the annotation file, so those glosses must be re-created. Once they are re-created, the dropping issue should not reoccur.

**Comment by hammondcl** [comment] 2017-02-27 16:41
There have not been any new drops, so I think this can be closed

**Comment by gregorydimitriadis** [comment] 2017-08-21 16:20
Reopening for further investigation.

**Comment by cneidle** [comment] 2017-08-22 14:21
another example - file 110 U 34
![screen shot 2017-08-22 at 10 20 14 am](https://user-images.githubusercontent.com/13629122/29570169-a741b078-8723-11e7-85a5-d0607a7c0605.png)

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-06 18:16
As of ignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

I believe the issues with displaying handshapes has been resolved for one frame glosses.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-06 18:17 UTC
Labels: bug, priority HIGH
