### ISSUE TITLE
Gloss Window - more notes on default selections

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#50] opened 2015-11-06 14:55 UTC
- If fingerspelled or loan sign or number sign:
  - By default:   1-handed
  - No selection for same start and end handshapes (grey out the selection box)
  - If changed to 2-handed, also check the marked number of hands box.
    - (and uncheck that box if the user switches back from 2-handed to 1-handed). 
  - If changed to 2-handed, the default is same handshapes on both hands.
- If lexical:
  - By default:   2-handed
    - Same start and end hand shapes
    - Same handshapes on both hands  
- The passive base arm should be grayed out for 1-handed signs.
  - For 2-handed signs, it should be an option, but unchecked by default.  
- For classifiers
  - By default:  2-handed, same handshapes (i.e., same as for lexical).
- For gestures
  - By default:  1-handed.
  - If the user switches to 2-handed, then the default should be same handshapes on both hands and same start and end handshapes.

---
- As is already implemented, if you’re dealing with a 2-handed lexical
  sign with DIFFERENT handshapes on both hands, then there is a
  very reduced set of handshape options normally for the non-dominant hand.
- But the user has the option of opening the regular, full handshape selection
  in case a different handshape is used.
- The full handshape options should be available for both hands, however,
  for gestures and classifiers.  (Not sure if that is in the current implementation.)

---
- In addition to the above, we also agreed to:
  - Move the Number Sign radio button to the first row and move the Name Sign checkbox to the second row.

**Comment by blazetravis** [comment] 2015-11-17 18:33
Some observations (all enhancements above now working, unless otherwise noted below):

### If fingerspelled or loan sign or number sign:
- No selection for same start and end handshapes (grey out the selection box)

I'm not so sure this is the right idea. Fingerspelled signs are always going to change handshape, so the greyed-out default should probably **not be** "same START/END hs." Further, some fingerspelled words DO end with the same start and end handshape, such as "BOB," so the issue is complicated.

### For gestures:
- By default, 1-handed
- If the user switches to 2-handed, then the default should be same handshapes on both hands and same start and end handshapes.

For gestures, it might be ok to have the program have a default number of hands, but in reality most gestures don't. Some are traditionally signed with one had, while others are signed with 2. Further, when toggling between one-handed and two-handed, the program should probably **not** automatically populate the marked number of hands option for this reason. Also, for one-handed gestures, the same START/END hs option is greyed out here, and this should **not** be the case. Gestures like "Forget it" change handshape over the course of the gloss.

### As is already implemented, if you’re dealing with a 2-handed lexical sign with DIFFERENT handshapes on both hands, then there is a very reduced set of handshape options normally for the non-dominant hand.

Can the "Rlxd" handshape be added to this reduced options list, please?

### The full handshape options should be available for both hands, however, for gestures and classifiers. (Not sure if that is in the current implementation.)

This is _not_ currently the case. Even with gesture or classifier marked for the gloss, the default list displayed for different two-handed is the same as that of 2-handed lexical. The non-dominant hand shows the limited list by default, so the user must manually click to display all options every time.

**Comment by cneidle** [comment] 2015-11-17 18:52
Hi,

Let me comment on this.

> On Nov 17, 2015, at 1:33 PM, blazetravis notifications@github.com wrote:
> 
> Some observations (all enhancements above now working, unless otherwise noted below):
> 
> If fingerspelled or loan sign or number sign:
> 
> No selection for same start and end handshapes (grey out the selection box)
> The selection box should show no text.

It is irrelevant whether or not the start and end handshapes are the same,
so this choice should be removed, in favor of no text showing there.

> I'm not so sure this is the right idea. Fingerspelled signs are always going to change handshape, so the greyed-out default should probably not be "same START/END hs." Further, some fingerspelled words DO end with the same start and end handshape, such as "BOB," so the issue is complicated.
> 
> For gestures:
> 
> By default, 1-handed
> If the user switches to 2-handed, then the default should be same handshapes on both hands and same start and end handshapes.
> For gestures, it might be ok to have the program have a default number of hands, but in reality most gestures don't. Some are traditionally signed with one had, while others are signed with 2.

Yes, that is true.  But something needs to appear; the user can change it.
So I think it is fine to have 1-handed appear until/unless the user changes
it to 2-handed, which is easy.  (That is the sense in which this is the default setting.)

> Further, when toggling between one-handed and two-handed, the program should probably not automatically populate the marked number of hands option for this reason.

Agreed.  No “marked number of hands” should be triggered automatically
for gestures.

This makes sense when fingerspelled signs are changed from 1-handed
to 2-handed, since fingerspelled signs really are marked if they are 2-handed.
But for gestures, there is no inherent markedness with respect to number of hands
(which is different from determining the default setup for annotations).

> Also, for one-handed gestures, the same START/END hs option is greyed out here, and this should not be the case. Gestures like "Forget it" change handshape over the course of the gloss.

Agreed.

Gestures should allow selection of same or different start/end handshape,
with same start and end handshape being the default (i.e., what is shown
until/unless the user changes it).

**Comment by gregorydimitriadis** [comment] 2015-11-17 19:39
I can make these edits relatively quickly, so I'll be doing that shortly.

One question, what is the Rlxd handshape?

**Comment by cneidle** [comment] 2015-11-17 19:41
Handshape 093 here:  http://www.bu.edu/asllrp/cslgr/pages/ncslgr-handshapes.html http://www.bu.edu/asllrp/cslgr/pages/ncslgr-handshapes.html

As I recall, there was another unmarked handshape missing there.

Blaze, do you recall which one is missing?   (I think it was one in the B or 5 family… ) 
Can you remind me which ones are included there?

Thanks!
  Carol

**Comment by blazetravis** [comment] 2015-11-17 20:04
Currently Included:
- 1, B, O, 5, B-L, S, A, **The image of 5-C, but the incorrect label of only "C"**, U/H

I think it was the 5-C that was missing. But since the image for that handshape is being displayed, perhaps what needs to be done is alter the label to the correct "5-C" and _add_ the real "C" hand shape with the correct label.

**Comment by cneidle** [comment] 2015-11-17 20:20
Hi Blaze,

Thanks!

Yes - if the wrong image is showing up for 5-C, then that is a bug
and should be fixed!

And yes, it would be good to include both C and 5-C in the set of
unmarked handshapes.

THANKS AGAIN,
Carol

**Comment by gregorydimitriadis** [comment] 2015-11-18 20:22
I've made the edits commented on above, and will be pushing the code out soon. Leaving this issue open  for now.

**Comment by blazetravis** [comment] 2015-11-23 18:39
This Bug and Enhancement Combo is fixed and completed. Looks great, Greg.

**Closed as completed** 2015-11-23 19:06 UTC
Labels: bug, complete
