### ISSUE TITLE
Disappearing morp info data

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#339] opened 2020-04-29 22:56 UTC
Working in MM file 051518 sentences U23: When entering in the data for the gloss PRISON the hand shapes on the right and left are different. When selecting this gloss from the sign bank the morph info window does not display that the sign is two handed or that the hand shapes on either hand is different. When trying to enter the hand shapes/info manually and selecting the "Bypass signbank Check" button, the hand shapes in the morph info window disappear. 

![Screen Shot 2020-04-29 at 3 50 47 PM](https://user-images.githubusercontent.com/38887034/80654708-c157aa80-8a31-11ea-9eee-4153c9d79ab9.png)

![Screen Shot 2020-04-29 at 3 50 56 PM](https://user-images.githubusercontent.com/38887034/80654726-d03e5d00-8a31-11ea-9138-0551e5e8e88b.png)

![Screen Shot 2020-04-29 at 3 51 03 PM](https://user-images.githubusercontent.com/38887034/80654741-d8969800-8a31-11ea-9083-114b10158fa2.png)

![Screen Shot 2020-04-29 at 3 50 31 PM](https://user-images.githubusercontent.com/38887034/80654745-db918880-8a31-11ea-80e5-6be72307a0f9.png)

**Comment by gregorydimitriadis** [comment] 2020-04-30 15:56
@bugspotter33 can't seem to reproduce the disappearing aspect here. What were the exact steps taken? (and does it happen every time?)

The sign bank file itself might be an issue here - if it is labelled as "same left/right" then that is what it will show up as in SignStream

**Comment by tessdekker** [comment] 2020-10-29 00:08
Working on Jonathan file #91 utterances 10 and 38, when entering the hand shape data into the morph info window, and when trying to select "Enter," the event lines show up for both the right and left hands, but the hand shapes. The lexical information shows up with no issues, just not the hand shapes. 
<img width="237" alt="Screen Shot 2020-10-26 at 7 49 40 PM" src="https://user-images.githubusercontent.com/61060581/97509686-598b0980-1959-11eb-93c5-bdd3b315bf4d.png">

**Comment by cneidle** [comment] 2020-10-29 14:38
Hi Tess and Indya,

I’m a bit confused, because I looked at the two utterances, and the handshapes are there:





Can you explain further?

Are you still having this problem?

Thanks,
 Carol

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-09 05:12
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Closing this issue.  The handshapes now show up.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-09 05:12 UTC
Labels: question
