### ISSUE TITLE
Morph-Phon Open /w Gloss Unselected

### ISSUE THREAD

**Issue by douglas-motto-at-rutgers** [DCS-LCSR/SignStream3#661] opened 2023-02-24 22:06 UTC
1. Selecting a gloss and opening the morph-phon window for it should lock the selection of that gloss in utterance window.

Currently create gloss.  Select it (it is red). Open morph-phon for it.  You should not be able to select another gloss.  Nor deselect the current gloss.  Until the morph-phon window is closed.

**Comment by douglas-motto-at-rutgers** [comment] 2023-02-24 22:08
2. Created two 2-handed glosses "LEFT" and "RIGHT".  Was able to select dom gloss line of "RIGHT" .  Saw "RIGHT" in red.  Opened morph-phon window for it.  now clicked on dom hand line of "LEFT"...Saw "LEFT" in red....while the morphon-phon window for RIGHT is still open.  changed name of entry from RIGHT to NEWRIGHT.  clicked "bypass sign bank check". 

the RIGHT gloss changed its name to NEWRIGHT.

but the morphon window was still open (or i reopened)....and now it doesn't display its handshapes that it previously had (perhaps a different issue).

**Comment by douglas-motto-at-rutgers** [comment] 2023-02-24 22:10
3. another example of weirdness.

create gloss...select gloss (see it in red) open morphon

You can add new glosses in the utterance window while the morph-phone window is open.

When the current gloss becomes unselected...and then clicked "bypass"...weird things happen.

**Comment by douglas-motto-at-rutgers** [comment] 2023-02-24 22:13
another example of weirdness.

create gloss...select gloss (see it in red)...open morphon

You can also select other non-manual fields...and the original gloss becomes unselected

again....clicking bypass it doesn't display its handshapes that it previously had (perhaps a different issue). 

When the current gloss becomes unselected...and then clicked "bypass"...weird things happen.

**Comment by douglas-motto-at-rutgers** [comment] 2023-02-24 22:15
checking to see if this happens in the latest pre-release version

**Comment by douglas-motto-at-rutgers** [comment] 2023-02-24 22:20
yes in latest...and possibly earlier.

Looks like anytime the morph-phon is open...and the gloss gets deselected...bad things happen.

**Comment by douglas-motto-at-rutgers** [comment] 2023-02-24 22:23
confirmed in 3.4.0

**Comment by gregorydimitriadis** [comment] 2023-02-27 15:12
@douglas-motto-at-rutgers I cannot reproduce. Can you list exact steps which were taken? I cannot even click a different gloss while the MorphPhon window is open. I do not know where the underscores before LEFT and RIGHT, in your example, are referring to.

I can reproduce creating a new gloss while MorphPhon is open, but haven't seen any detrimental effects from it.

Testing on prerelease version "2023_02_24_0928"

@cneidle thoughts? Can you reproduce?

**Comment by cneidle** [comment] 2023-02-27 16:17
A) I cannot reproduce the issues I have labeled as (1) and (2) above.  I am able to create a new gloss (3 above) while the morph-phon window is open, which should obviously not be allowed. I am also able to select non-manual events (4 above), which also should not happen.  When I select a non-manual event with the Morph-Phon window open, handshapes having been selected, sometimes (but not consistently) the handshapes disappear from that window.

B) As I was trying the things above, Sign Bank check often was not working.  I was able to use the Enter button for things that do not exist in the Sign Bank.

C) When I created a new gloss, selected it, and tried to use the left and right arrows to advance the video, they did not work.

I imagine that (B) and (C) are their own issues, but I don't know if these problems are related to the things I was trying with the Morph-Phon window.

**Comment by cneidle** [comment] 2023-02-27 16:44
What SHOULD happen is that when the Morph-phon window is open, the selected gloss should not be able to be deselected (which means that nothing else should be able to be selected).  It should be possible to use the navigation buttons, e.g., to play the selected gloss, to go to the beginning and end of that gloss, etc., but the gloss should remain selected.  Thanks.

**Comment by douglas-motto-at-rutgers** [comment] 2023-02-27 19:17
Per (B)...see https://github.com/DCS-LCSR/SignStream3/issues/523

**Comment by gregorydimitriadis** [comment] 2023-02-28 16:48
@cneidle Doug showed me the issue. Here is how to reproduce:

* make the example as he had, with 2 two-handed glosses annotated
* click to open the MP window for the first gloss, then select the "dom hshape" or "ndom hshape" line for the second gloss
* then attempt to enter/bypass out of the MP window - this is an error here
* if you keep hitting bypass, I can see the handshapes disappear from the first gloss.

So - first, can you reproduce that as well? And secondly, priority to fix in this release or no?

**Comment by douglas-motto-at-rutgers** [comment] 2023-02-28 16:55
Also as Carol stated in "A" above.  If the MP window is open for any gloss and a non-manual hand is selected, keep hitting bypass in the MP will result in the handshapes disappearing from the gloss.

**Comment by cneidle** [comment] 2023-02-28 16:57
Yes, I can reproduce the disappearance of handshapes by following those instructions.

It would be a fairly high priority to lock the gloss selection when the Morph-phon window has been opened, disallowing selecting anything else until the Morph-phon window has been closed.  do you have a sense of how big a job this would be?  Thanks.

**Comment by gregorydimitriadis** [comment] 2023-02-28 17:10
@cneidle I will check it out this afternoon. If simple I'll fix it outright.

**Comment by gregorydimitriadis** [comment] 2023-03-01 20:48
Was able to implement a fix to allow glosses to not be de-selected during MorphPhon editing, and other events to not be selected during this time. Marking as code complete for now.

**Comment by cneidle** [comment] 2023-03-01 22:36
Terrific.  Thanks very much.

**Comment by gregorydimitriadis** [comment] 2023-10-02 19:26
Released in 3.4.1

**Closed as completed by gregorydimitriadis** 2023-10-02 19:26 UTC
Labels: bug, released, data concern, severity HIGH
