### ISSUE TITLE
Version 3.4.1 pre-release - In utterance window, box that appears for gloss text does not go away

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#611] opened 2022-12-21 20:26 UTC
It happens repeatedly that the box that appears for gloss text does not go away if no gloss text is typed in.

It persists, appearing in other windows as well.

<img width="1278" alt="Screen Shot 2022-12-21 at 3 01 54 PM" src="https://user-images.githubusercontent.com/13629122/208996227-ab668692-ae0e-4e66-833a-96576ba13f29.png">

<img width="794" alt="Screen Shot 2022-12-21 at 3 01 20 PM" src="https://user-images.githubusercontent.com/13629122/208996251-8b8701e0-3e66-4c11-a589-3dc5dcae29e2.png">

<img width="723" alt="Screen Shot 2022-12-21 at 3 23 58 PM" src="https://user-images.githubusercontent.com/13629122/208996534-72d69ad2-3b70-40f8-8779-c495710bad65.png">

I have also experienced some weird behavior in trying to set start and end points of text for glosses; not sure if this is related.  I will see if I can replicate that.

**Comment by cneidle** [comment] 2022-12-21 20:38
So, I option-click, creating that box.  Then I do something else, like entering morph-phon information in another gloss.  If I then use the keyboard, the text gets typed in that ghosted box, which has remained active.

<img width="589" alt="Screen Shot 2022-12-21 at 3 32 42 PM" src="https://user-images.githubusercontent.com/13629122/208998077-7bc97725-8a03-4ff9-9713-2c0d110f8f48.png">

it is possible to create multiple such boxes by option clicking in more than one place.

If I hit a carriage return without entering any text, in the hope of making that box go away, 
I get an error message, but after I dismiss the error message, that box goes away..

<img width="755" alt="Screen Shot 2022-12-21 at 3 33 22 PM" src="https://user-images.githubusercontent.com/13629122/208998275-8aaaf402-f313-4d52-aecb-8b0e6b6210db.png">

The text in the box remains if no carriage return has been entered, but it floats and does not stay with the rest of the field if the window is moved.

<img width="789" alt="Screen Shot 2022-12-21 at 3 34 28 PM" src="https://user-images.githubusercontent.com/13629122/208998432-871430db-10d3-4af5-87a1-8cc5f3063012.png">

**Comment by cneidle** [comment] 2022-12-21 21:20
If I create the box in Utterance 3, e.g., then go to database view, the box is there.  If I type in the box and hit carriage return, the text gets entered back in utterance 3.

<img width="931" alt="Screen Shot 2022-12-21 at 4 18 21 PM" src="https://user-images.githubusercontent.com/13629122/209004598-ec764446-c77b-4aaf-af2c-f7f870403ab8.png">

<img width="1080" alt="Screen Shot 2022-12-21 at 4 18 31 PM" src="https://user-images.githubusercontent.com/13629122/209004624-d7061ba6-5ae1-4cc2-b220-763c0b944ee0.png">

<img width="854" alt="Screen Shot 2022-12-21 at 4 18 42 PM" src="https://user-images.githubusercontent.com/13629122/209004632-c834c745-40e5-4137-87c8-f614c87254a6.png">

**Comment by douglas-motto-at-rutgers** [comment] 2023-01-06 10:05
This has been observed for at least the past 3 years.  While it happens occasionally, it is difficult to reliably reproduce...and therefore identify the problem.  Investigating code did not expose suggestions about why this happens.  May be due to old JavaSwing library implementation.

**Comment by cneidle** [comment] 2023-01-09 17:35
This problem is MUCH worse in version 3.4.1 than in previous versions.  It happens for me 100% of the time.  And the ability to enter data into that persisting field even from the database view is definitely something I have not previously seen, although that box has *occasionally* remained in earlier versions.  In any case, there is no problem for me in reproducing this in 3.4.1.  It also persists outside of the SignStream windows, if the SignStream windows are moved.

<img width="1045" alt="Screen Shot 2023-01-09 at 12 34 03 PM" src="https://user-images.githubusercontent.com/13629122/211371113-37bc4507-97a3-445a-8793-8afed8713de0.png">

**Comment by cneidle** [comment] 2023-01-21 18:47
This has also happened to me in 3.4.0 with text box for changing utterance name.

<img width="1130" alt="Screen Shot 2023-01-21 at 12 46 43 PM" src="https://user-images.githubusercontent.com/13629122/213882436-3e400ef4-4cf0-4e64-8ee0-51f45056e0d5.png">

<img width="1179" alt="Screen Shot 2023-01-21 at 12 46 33 PM" src="https://user-images.githubusercontent.com/13629122/213882441-c6ac34c0-d2e5-42c8-b0af-08b27b9952c0.png">

**Comment by gregorydimitriadis** [comment] 2023-01-25 15:36
I believe this to be due to a recent change made in #527 

Moving this issue into the upcoming milestone release in order to resolve it as part of that issue.

**Comment by douglas-motto-at-rutgers** [comment] 2023-02-07 13:33
It's at least not as easily reproducible now in pre_2023_02_03....although the old problem of it occasionally happening may still exist.

**Comment by cneidle** [comment] 2023-02-13 17:29
see #649 and #647 and #624 and #625

**Comment by cneidle** [comment] 2023-02-18 18:21
#638 and #608 also related

**Comment by gregorydimitriadis** [comment] 2023-10-02 18:52
Released in 3.4.1

**Closed as completed by gregorydimitriadis** 2023-10-02 18:52 UTC
Labels: bug, released, severity HIGH, severity LOW
