### ISSUE TITLE
Weird colors in version 3.3.5

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#378] opened 2020-12-16 16:01 UTC
This is what the utterance window has looked like up to now (this from 3.3.4), i.e., the lines for glosses are black:

<img width="499" alt="Screen Shot 2020-12-16 at 10 58 50 AM" src="https://user-images.githubusercontent.com/13629122/102373080-d4ea5e00-3f8d-11eb-91d1-669dd17513da.png">

In the new version, the lines are mostly blue.  I have no objection to having the lines appear in blue, except that it is quite inconsistent.  Not sure if this is an intentional change, or... ??

<img width="429" alt="Screen Shot 2020-12-16 at 10 56 21 AM" src="https://user-images.githubusercontent.com/13629122/102373239-fd725800-3f8d-11eb-9ca7-808a40c082c3.png">

<img width="323" alt="Screen Shot 2020-12-16 at 10 56 51 AM" src="https://user-images.githubusercontent.com/13629122/102373240-fd725800-3f8d-11eb-836a-c5f86ce99725.png">

<img width="725" alt="Screen Shot 2020-12-16 at 10 57 27 AM" src="https://user-images.githubusercontent.com/13629122/102373241-fd725800-3f8d-11eb-8a85-0bb8c291721e.png">

**Comment by gregorydimitriadis** [comment] 2020-12-16 16:16
@cneidle Hmm..I see what you're saying. I didn't notice that, and I think I know the cause. Will address this.

**Comment by cneidle** [comment] 2020-12-16 17:36
Perhaps a related problem?  Selecting HIT in this case failed to de-select (or at least to de-highlight) EIGHT:

<img width="320" alt="Screen Shot 2020-12-16 at 12 35 27 PM" src="https://user-images.githubusercontent.com/13629122/102384996-51376e00-3f9b-11eb-99b5-4df3ea740921.png">

**Comment by cneidle** [comment] 2020-12-16 17:39
More on above:  Clicking elsewhere de-selects but does not de-highlight EIGHT.  But note that with nothing selected, the Play Event button is grayed out, but the Play Entity button is not, although clicking on the Play Entity button has no effect.

<img width="1015" alt="Screen Shot 2020-12-16 at 12 37 50 PM" src="https://user-images.githubusercontent.com/13629122/102385282-a83d4300-3f9b-11eb-96a8-3a3dd9d35bc6.png">

**Comment by cneidle** [comment] 2020-12-17 15:47
Note about priorities:  these issues with selection (and display) must be resolved prior to the next public release.  Thanks !!

**Comment by cneidle** [comment] 2021-01-19 01:59
FWIW, it looks like the extra red color comes right after the now-red plus signs in compounds.  Perhaps the change in color for the + is not properly terminated... (That doesn't explain the blue appearing all over, of course.)

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-09 09:06
As SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Not completely fixed.

Just after going from 1->2 handed...before unfocusing...the hand lines are still blue.

Keeping open.

**Comment by gregorydimitriadis** [comment] 2021-05-25 21:13
Will be fixed in versions:
3.7.0_pre_2021_05_25_1704_16f12c84
4.1.0_pre_2021_05_25_1708_694156a2

**Closed as completed** 2021-05-25 21:14 UTC
Labels: bug, in progress, priority MED
