### ISSUE TITLE
Handshape can't be added because "event chain overlap"

### ISSUE THREAD

**Issue by geograil** [DCS-LCSR/SignStream3#86] opened 2016-06-15 17:52 UTC
File: Cory 108 Utterance 47

We started with the complete file and deleted the main glosses. I was working on adding them back in and when I went to put in the handshapes for LEARN, it gave me a pop up box that says "Warning: The events chain cannot overlap with another events chain. You must adjust the boundaries of the adjacent events chain and then try again." However, there were no other glosses adjacent to it. 

Steps:
- Entered the gloss and set the start/end boundaries
- Opened morph-phon info and selected relevant categories: Two-handed sign with different L/R handshapes and same start/end handshape for both hands
- Added in handshapes "flat-o" for right hand and "5-C-L" for left hand

![screen shot 2016-06-15 at 1 47 00 pm](https://cloud.githubusercontent.com/assets/19953651/16091024/cc87e1e6-32ff-11e6-8b66-3757f01e13d7.png)
- Hit enter and got the warning box

![screen shot 2016-06-15 at 1 47 16 pm](https://cloud.githubusercontent.com/assets/19953651/16091029/d1eeb1dc-32ff-11e6-952b-dd4a23d7663f.png)

If you click "Ok" in the warning box, you have to do it again and just get the same result.

**Comment by gregorydimitriadis** [comment] 2016-06-15 18:18
Hi Graham - did this same error not occur for the creation of the other two main glosses there? (#IF and IX-3p:i) I assume those were created after all of the main glosses were initially deleted.

**Comment by geograil** [comment] 2016-06-15 18:31
Correct; I was testing further since I've posted this and it appears the error only happens with two-handed signs. The two showing up are both one handed so I assume that is why they added in okay

**Comment by gregorydimitriadis** [comment] 2016-06-15 18:50
Thanks. Does the error still occur if, after first deleting all of the main glosses from the utterance, you return to the DatabaseView and then click back into that same utterance and attempt to add any two-handed sign then?

This wouldn't be a complete fix to the error but possibly a temporary workaround until I can better diagnose and solve it.

**Comment by geograil** [comment] 2016-06-15 19:22
We are having trouble reproducing the error after restarting Sign Stream a few times, but if we run into it again, we will try the workaround. Thanks!

**Comment by gregorydimitriadis** [comment] 2016-12-08 16:31
Hi @geograil @hammondcl

Has this issue ever reoccurred since the initial report? I believe the root cause to have been related to bugs #104 and #105, so since I've just fixed those I have reason to think this would be fixed as well. I also do not have the Cory 108 file to test, if someone can please email me that.

**Comment by geograil** [comment] 2016-12-09 16:28
I don't recall specific instances, but I feel like it may have. However, I'm not positive about that, so I guess we can assume it fixed for now and we will let you know if it happens again?

I'll try to email that file to you right now

**Comment by gregorydimitriadis** [comment] 2016-12-12 16:10
Thanks Graham - I was able to reproduce the same error in the file you gave me. It turns out it was a different issue, but I have now also fixed this separate issue - the fix will be included in the next package release (expected within the next few days)

**Comment by hammondcl** [comment] 2017-03-01 18:33
This has not happened recently

**Closed as completed** 2017-03-01 19:21 UTC
Labels: complete
