### ISSUE TITLE
Trying to open a file and it is blank when opened

### ISSUE THREAD

**Issue by carlyzx9** [DCS-LCSR/SignStream3#89] opened 2016-06-27 19:12 UTC
I've been working on the Rachel 66 file for a week or two and it has opened normally every other time I've opened it, but today I went to go open it and it was blank. I checked the Files to Work on Excel sheet and it didn't have any particular notes that would give me any clues as to why it wouldn't open.

Steps:
I opened Sign Stream.
![screen shot 2016-06-27 at 2 30 17 pm](https://cloud.githubusercontent.com/assets/19909811/16392183/9308969a-3c78-11e6-985d-97d5b5eab150.png)

I clicked collection --> open --> CURRENT, and then clicked on the Rachel 66 file. 
![screen shot 2016-06-27 at 2 30 49 pm](https://cloud.githubusercontent.com/assets/19909811/16392251/f73277da-3c78-11e6-8042-81b31c529170.png)

Then it opened with a blank screen instead of showing all of the utterance numbers.
![screen shot 2016-06-27 at 2 30 58 pm](https://cloud.githubusercontent.com/assets/19909811/16392273/177c5ede-3c79-11e6-9670-487fdf7b62fc.png)

**Comment by geograil** [comment] 2016-07-01 13:55
A small detail about this is also that it doesn't appear that the file is actually opening at all; the title of what is open has not changed from "Collection_......". Usually the title does change once it has opened something.  

I'm not sure if that makes a significant difference, but it's just something I noticed in the screenshots.

I just tried to open it and it did the same thing. I believe there isn't a macro unit attached to the file because it looks the same as when Jonathan 96 is opened -- that file doesn't have the macro unit attached. Since you were working with it before, it's odd that it suddenly has problems, but maybe it's the same issue?

**Comment by gregorydimitriadis** [comment] 2016-07-05 18:45
Not sure if this collection is still causing issues, but if so: does this collection, when opened, have videos attached? If not a single video is associated with the collection, then that could be the explanation for this display.

**Comment by carlyzx9** [comment] 2016-07-05 18:49
There are no videos opening along with the collection.

**Comment by cneidle** [comment] 2016-07-05 18:53
> On Jul 5, 2016, at 2:49 PM, carlyzx9 notifications@github.com wrote:
> 
> There are no videos opening along with the collection.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub https://github.com/DCS-LCSR/SignStream3/issues/89#issuecomment-230567880, or mute the thread https://github.com/notifications/unsubscribe/AM_2wiMWSe2V8F_axYGBdDcAlYvqozfDks5qSqdBgaJpZM4I_aSt.
> 
> Carly - 

You may need to relocate the videos.

If you don’t know how to do that, please phone me at x6218 and
I’ll come down and show you.

thanks,
 Carol

**Comment by carlyzx9** [comment] 2016-07-05 19:04
Carol here.  This is NOT a problem of her simply needing to relocate the video file.
Greg - this is the same situation as what we looked at together when I was at Rutgers.  What opens is a window with the title "Collection... " in the title bar rather than the name of the file that should have opened.  Nothing else is visible and there is no way to access any Macro Unit, to edit.

This is seeming to be a recurrent problem - with files becoming unusable because of something weird that happens when they are saved, sometimes.  The file seems unusually large, so it may be what we noticed before where a second copy of the annotations is somehow getting saved...  

Thanks in advance for your help in sorting this out!

**Comment by carlyzx9** [comment] 2016-07-05 19:10
Just sent the file via email.

**Comment by gregorydimitriadis** [comment] 2016-07-05 19:11
Thanks Carol. I'll be checking out all these saving/opening issues collectively shortly.

**Comment by gregorydimitriadis** [comment] 2016-07-27 20:55
@cneidle @carlyzx9 I have a feeling the issues with these files may have had to do with the video processing library (xuggler) since I was not able to reproduce any of these issues, but I did notice some of the same behavior when the videos were not present/locatable from my local collections

Could I ask you to try opening these collections with the very latest signstream_uat package, and see if these issues still occur?

**Comment by hammondcl** [comment] 2016-09-28 14:45
Hello,

I've been playing around with this file this morning and have noticed some interesting things:

1) If you open the file normally (Collection --> Open --> Current --> Rachel 66), the normal SignStream window opens and shows that there are utterances present, but there are no videos attached.

![screen shot 2016-09-28 at 10 33 23 am](https://cloud.githubusercontent.com/assets/15836242/18917876/0cee0198-8567-11e6-85f5-5734800b79fa.png)

Upon opening U1, nonmanuals seem to be in place, but main glosses have no handshapes and trying to navigate through utterances either by using the "Next/ Previous Utterance" buttons or by scrolling does not work. You can click and scroll, but the nonmanuals and glosses do not change. As you can see in this screenshot, the program has U14, 15, and 16 highlighted as the selected utterance (it is unusual to have more than one selected) and the information shown is actually the coding from U1

![screen shot 2016-09-28 at 10 35 39 am](https://cloud.githubusercontent.com/assets/15836242/18918140/d6a9b306-8567-11e6-9130-dd0b19b4f035.png)

2) If I manually attach the videos, they do open and you can frame through them, but no utterances appear in the actual SignStream window and the title of the screen does not change correctly. Adjusting the zoom bar has no effect. 

![screen shot 2016-09-28 at 10 42 19 am](https://cloud.githubusercontent.com/assets/15836242/18918344/7e0a4b1a-8568-11e6-831b-ff9f07ddeb0a.png)

**Comment by gregorydimitriadis** [comment] 2016-09-28 17:26
During a skype call today with Chelsea and Graham, we saw that opening the existing collection (which initially loads no videos) and re-selecting the videos from their proper directories from within the 'Edit Macro Unit' solves this problem. Closing this issue out now.

**Closed as completed by gregorydimitriadis** 2016-09-28 17:26 UTC
Labels: bug
