### ISSUE TITLE
Search Function: the value dropdown menu for participant stays visible

### ISSUE THREAD

**Issue by geograil** [DCS-LCSR/SignStream3#101] opened 2016-07-26 19:10 UTC
I was testing the new SS patch sent out today and the designated issues were resolved. This may be due to the issue in bug 85 that causes the non-manual menu to remain displayed, but I noticed that when you move the main search box open while the dropdown under participant is still open, that dropdown box stays where it is and does not move with the box (how the non-manual options remain displayed). However, it does go away when clicking into another part of signstream (videos, coding panel) or another program such as google chrome.

![screen shot 2016-07-26 at 3 03 30 pm](https://cloud.githubusercontent.com/assets/19953651/17151694/8c3be912-5342-11e6-8754-75788b485117.png)

![screen shot 2016-07-26 at 3 03 43 pm](https://cloud.githubusercontent.com/assets/19953651/17151768/d5750d5c-5342-11e6-94ce-cc7bc92b99ce.png)

**Comment by gregorydimitriadis** [comment] 2016-07-26 19:13
Graham - are there any participants loaded into this collection? More specifically - are any participants listed in the Edit Macro Unit screen? Only names from that list will show up in the search panel participant combobox.

**Comment by geograil** [comment] 2016-07-26 19:21
Ah, okay. I didn't know about that part. There weren't any on the list in the Edit Macro Unit. I temporarily added Rachel's name and tested the search box and it worked properly. Sorry for the confusion! 

The little dropdown menu does still stay visible though, so that part of this is still relevant. Do you want me to edit this issue report to only include the part about the menu being visible?

**Comment by gregorydimitriadis** [comment] 2016-07-26 19:23
No problem! Please do!

**Comment by gregorydimitriadis** [comment] 2017-01-25 15:36
Along with issue #97, after the changes made for Sprint 20, I am unable to reproduce this issue, so I will mark this as complete. If the issue re-appears, post a comment here noting this and I'll take another look into it.

**Comment by hammondcl** [comment] 2017-01-25 16:19
Hi Greg, this issue is fixed on our end as well!

**Closed as completed** 2017-01-25 17:29 UTC
Labels: bug, complete
