### ISSUE TITLE
Can't open/edit a specific utterance 

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#275] opened 2019-07-20 03:15 UTC
I am working in Deaf Speech Ben file U39 and I keep clicking on the utterance to open to add the non-manuals and I get sent to U20 and U21 and can't scroll within the program to get to U39

![Screen Shot 2019-07-19 at 11 10 39 PM](https://user-images.githubusercontent.com/38887034/61573336-f5ea0f00-aa7a-11e9-8914-8b637ff1f7dd.png)

![Screen Shot 2019-07-19 at 11 10 27 PM](https://user-images.githubusercontent.com/38887034/61573339-fb475980-aa7a-11e9-993b-76f286517a7e.png)

**Comment by bugspotter33** [comment] 2019-07-20 03:18
I also tried opening the next utterance U40 and scrolling backwards from there but then it shows that the entire file has no non manuals at all for any of the utterances.

![Screen Shot 2019-07-19 at 11 16 43 PM](https://user-images.githubusercontent.com/38887034/61573362-7b6dbf00-aa7b-11e9-8e62-34fe828c0c04.png)

**Comment by bugspotter33** [comment] 2019-07-20 03:21
I closed and reopened SS and can now access the utterance but this is still a major concern as I'm not sure why it happened.

**Comment by bugspotter33** [comment] 2019-07-20 03:44
If I save my work in U39 come out of it to the Database view window and then click on it to open it jumps to another utterance and I can't scroll to it.

![Screen Shot 2019-07-19 at 11 43 57 PM](https://user-images.githubusercontent.com/38887034/61573568-1c11ae00-aa7f-11e9-96e1-fec1559c37a0.png)

**Comment by cneidle** [comment] 2019-07-20 04:03
You have a video file open when you are doing this?

**Comment by cneidle** [comment] 2019-07-20 11:17
Hi Indya,

Let’s look at this together this coming week :-)
I’m not able to reproduce the problem.

Just FYI, I’ll be in the office Monday through Thursday.

Thanks!

Best,
 Carol

**Comment by cneidle** [comment] 2019-07-20 11:19
Hi Indya,

Let’s look at this together this coming week :-)
I’m not able to reproduce the problem.

Just FYI, I’ll be in the office Monday through Thursday.

Thanks!

Best,
 Carol

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-07 18:39
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

seems like this could not be reproduced.

closing.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-07 18:39 UTC
Labels: question
