### ISSUE TITLE
Adding participant to collection without one causes issues

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#359] opened 2020-08-03 14:25 UTC
Per Carol:

> For a particular file, it appears fine.
However, adding a participant totally messes up the file.
I did it once, and virtually all annotations disappeared.
I tried it a second time, and only all hand information disappeared.

**Comment by gregorydimitriadis** [comment] 2020-09-28 19:22
@cneidle having difficulty reproducing this - what were the sequence of steps which brought about the problem?

**Comment by cneidle** [comment] 2020-09-29 14:44
I am also not able to reproduce this currently.  So let's close this for now and return to it if this problem recurs.  Hopefully we will not have files in the future that are missing a participant, in any case.  Thanks.

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-29 06:02
per last comment Closing.

**Closed as completed by douglas-motto-at-rutgers** 2021-05-29 06:02 UTC
Labels: bug, in progress, priority HIGH
