### ISSUE TITLE
Related to Wrong Morph-Info #216

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#232] opened 2018-06-11 22:57 UTC
Starting a new thread - because that one is already very long.

There are quite a few cases where, e.g., in file 50, a sign had previously been annotated as 1-handed, and it is displayed with handshapes for one hand, but the morph-phon window shows it as 2-handed.

We detected this because these files were not being parsed properly for uploading to the DAI.

I am sending the file with the first few of these fixed (and they seem to stay fixed when saved and then reopened) and the remainder not fixed, so you can see the problem.

NOT
<img width="1377" alt="screen shot 2018-06-11 at 6 40 26 pm" src="https://user-images.githubusercontent.com/13629122/41261028-f1c86ba8-6da7-11e8-8d8b-74611c992195.png">

LIKE

<img width="1056" alt="screen shot 2018-06-11 at 6 41 31 pm" src="https://user-images.githubusercontent.com/13629122/41261051-04f53580-6da8-11e8-9d24-e303678bbe70.png">

PINEAPPLE

<img width="1368" alt="screen shot 2018-06-11 at 6 41 03 pm" src="https://user-images.githubusercontent.com/13629122/41261037-fa129d4c-6da7-11e8-8d70-6100a5a818f8.png">

But this is very weird:  The ones I haven't fixed open up showing incorrect information,
but then if I open up other signs and go back to that one, they then show up correctly with respect to the display of handshapes on only one hand, without my having changed anything, but they are still misclassified as 2-handed (when they had originally been coded as 1-handed).

So in Utterance 14, the first 4 signs are flaky in this respect!

<img width="1063" alt="screen shot 2018-06-11 at 6 52 49 pm" src="https://user-images.githubusercontent.com/13629122/41261301-04fb8308-6da9-11e8-9ddc-82284645f83f.png">

<img width="886" alt="screen shot 2018-06-11 at 6 53 15 pm" src="https://user-images.githubusercontent.com/13629122/41261311-0bec4ab2-6da9-11e8-9525-1b80b03fb774.png">

[Rachel_2012-01-27_sc50-6-11.ss3.zip](https://github.com/DCS-LCSR/SignStream3/files/2092004/Rachel_2012-01-27_sc50-6-11.ss3.zip)

**Comment by gregorydimitriadis** [comment] 2018-06-12 15:56
Relates to #216

**Comment by gregorydimitriadis** [comment] 2018-09-20 18:00
@cneidle For the first three (not, like, pineapple) I see the same happening.

For FATHER - in the xml for the collection it is actually saved as "NO_OF_HANDS=2"

**Comment by gregorydimitriadis** [comment] 2018-09-20 20:16
Fixing some bag logic for setting 1/2 handed which should resolve one-handed signs showing up as two-handed in the MorphPhon

**Comment by cneidle** [comment] 2018-09-22 21:02
Ok - glad if you have fixed this.

**Comment by travisnguyen** [comment] 2018-11-29 19:41
Discrepancy: This bug has been noted as fixed in the release notes for 3.1.2, but has only been partially addressed.

**Comment by gregorydimitriadis** [comment] 2019-02-27 19:21
@cneidle @travisnguyen what is the current state of this issue?

**Comment by gregorydimitriadis** [comment] 2019-03-27 18:48
Hi @travisnguyen just checking in again - do you remember which part of this issue is not addressed?

**Comment by travisnguyen** [comment] 2019-03-27 22:00
@gregorydimitriadis My last comment was about a discrepancy between how the bug fix was described in the README.txt for version 3.1.2 ("fixed") and in the e-mail that Carol and I received that included a list of bug fixes in version 3.1.2 ("partially fixed").

In any case, I can't reproduce the issue using the first four signs of U14 in file 0050 (described by Carol earlier in this thread) or any other file. Currently using version 3.1.3.

**Comment by gregorydimitriadis** [comment] 2019-03-28 13:33
see comment here https://github.com/DCS-LCSR/SignStream3/issues/216#issuecomment-477596393

**Comment by douglas-motto-at-rutgers** [comment] 2021-05-07 16:04
This may be corrected as of
SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

But need to reverify requirements and implementation.

So leaving open for now.

**Comment by cneidle** [comment] 2021-10-15 22:56
is this fixed?

**Comment by gregorydimitriadis** [comment] 2022-09-22 19:35
Should be fixed - closing for now.

**Closed as completed by gregorydimitriadis** 2022-09-22 19:35 UTC
Labels: bug, enhancement, priority HIGH, released, PRI 1
